<?php
declare(strict_types=1);
namespace OCA\ReinhardtERP\Service;
use OCP\IDBConnection;
final class AttendanceService {
 public function __construct(private IDBConnection $db){}
 public function current(string $uid):?array{$q=$this->db->getQueryBuilder();$q->select('*')->from('re_erp_attendance')->where($q->expr()->eq('user_id',$q->createNamedParameter($uid)))->andWhere($q->expr()->isNull('clock_out'))->orderBy('id','DESC')->setMaxResults(1);$r=$q->executeQuery()->fetch();return $r?:null;}
 public function clockIn(string $uid,string $by):void{if($this->current($uid))throw new \InvalidArgumentException('Arbeitszeit läuft bereits.');$now=date('Y-m-d H:i:s');$id=$this->insert('re_erp_attendance',['user_id'=>$uid,'work_date'=>date('Y-m-d'),'clock_in'=>$now,'clock_out'=>null,'break_started_at'=>null,'break_minutes'=>0,'status'=>'working','created_at'=>$now,'updated_at'=>$now]);$this->audit($id,$uid,'clock_in',$by,null);}
 public function pause(string $uid,string $by):void{$r=$this->current($uid);if(!$r||$r['status']!=='working')throw new \InvalidArgumentException('Keine laufende Arbeitszeit zum Pausieren.');$now=date('Y-m-d H:i:s');$this->update((int)$r['id'],['break_started_at'=>$now,'status'=>'paused','updated_at'=>$now]);$this->audit((int)$r['id'],$uid,'pause',$by,null);}
 public function resume(string $uid,string $by):void{$r=$this->current($uid);if(!$r||$r['status']!=='paused'||empty($r['break_started_at']))throw new \InvalidArgumentException('Keine laufende Pause.');$mins=max(0,(int)floor((time()-strtotime((string)$r['break_started_at']))/60));$now=date('Y-m-d H:i:s');$this->update((int)$r['id'],['break_started_at'=>null,'break_minutes'=>(int)$r['break_minutes']+$mins,'status'=>'working','updated_at'=>$now]);$this->audit((int)$r['id'],$uid,'resume',$by,'Pause +'.$mins.' Min.');}
 public function clockOut(string $uid,string $by):void{$r=$this->current($uid);if(!$r)throw new \InvalidArgumentException('Keine laufende Arbeitszeit.');$mins=(int)$r['break_minutes'];if($r['status']==='paused'&&!empty($r['break_started_at']))$mins+=max(0,(int)floor((time()-strtotime((string)$r['break_started_at']))/60));$now=date('Y-m-d H:i:s');$this->update((int)$r['id'],['clock_out'=>$now,'break_started_at'=>null,'break_minutes'=>$mins,'status'=>'done','updated_at'=>$now]);$this->audit((int)$r['id'],$uid,'clock_out',$by,null);}
 public function day(string $uid,string $date):array{$q=$this->db->getQueryBuilder();$q->select('*')->from('re_erp_attendance')->where($q->expr()->eq('user_id',$q->createNamedParameter($uid)))->andWhere($q->expr()->eq('work_date',$q->createNamedParameter($date)))->orderBy('clock_in','ASC');$rows=$q->executeQuery()->fetchAll();$hours=0.0;$break=0;foreach($rows as $r){$end=!empty($r['clock_out'])?strtotime((string)$r['clock_out']):time();$b=(int)$r['break_minutes'];if($r['status']==='paused'&&!empty($r['break_started_at']))$b+=max(0,(int)floor((time()-strtotime((string)$r['break_started_at']))/60));$break+=$b;$hours+=max(0,($end-strtotime((string)$r['clock_in']))/3600-$b/60);}return ['rows'=>$rows,'hours'=>round($hours,2),'breakMinutes'=>$break,'current'=>$this->current($uid)];}
 public function week(string $uid,string $start):array{$end=date('Y-m-d',strtotime($start.' +6 days'));$q=$this->db->getQueryBuilder();$q->select('*')->from('re_erp_attendance')->where($q->expr()->eq('user_id',$q->createNamedParameter($uid)))->andWhere($q->expr()->gte('work_date',$q->createNamedParameter($start)))->andWhere($q->expr()->lte('work_date',$q->createNamedParameter($end)))->orderBy('work_date','ASC');$rows=$q->executeQuery()->fetchAll();$hours=0.0;foreach($rows as $r){$finish=!empty($r['clock_out'])?strtotime((string)$r['clock_out']):time();$b=(int)$r['break_minutes'];if($r['status']==='paused'&&!empty($r['break_started_at']))$b+=max(0,(int)floor((time()-strtotime((string)$r['break_started_at']))/60));$hours+=max(0,($finish-strtotime((string)$r['clock_in']))/3600-$b/60);}return ['rows'=>$rows,'hours'=>round($hours,2)];}
 public function saveManual(string $uid,string $date,string $clockIn,string $clockOut,int $breakMinutes,string $by,?string $note=null):int{
  if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||!preg_match('/^\d{2}:\d{2}$/',$clockIn)||!preg_match('/^\d{2}:\d{2}$/',$clockOut))throw new \InvalidArgumentException('Datum, Beginn oder Ende ist ungültig.');
  $start=strtotime($date.' '.$clockIn);$end=strtotime($date.' '.$clockOut);if($end<=$start)$end+=86400;$breakMinutes=max(0,$breakMinutes);if(($end-$start)<=($breakMinutes*60))throw new \InvalidArgumentException('Pause darf nicht länger als die Anwesenheit sein.');$q=$this->db->getQueryBuilder();$q->select('clock_in','clock_out')->from('re_erp_attendance')->where($q->expr()->eq('user_id',$q->createNamedParameter($uid)))->andWhere($q->expr()->eq('work_date',$q->createNamedParameter($date)));foreach($q->executeQuery()->fetchAll() as $existing){$es=strtotime((string)$existing['clock_in']);$ee=!empty($existing['clock_out'])?strtotime((string)$existing['clock_out']):time();if($start<$ee&&$end>$es)throw new \InvalidArgumentException('Der manuelle Anwesenheitseintrag überschneidet sich mit einer vorhandenen Stempelung.');}
  $now=date('Y-m-d H:i:s');$id=$this->insert('re_erp_attendance',['user_id'=>$uid,'work_date'=>$date,'clock_in'=>date('Y-m-d H:i:s',$start),'clock_out'=>date('Y-m-d H:i:s',$end),'break_started_at'=>null,'break_minutes'=>$breakMinutes,'status'=>'done','created_at'=>$now,'updated_at'=>$now]);
  $this->audit($id,$uid,'manual_entry',$by,trim((string)$note)?:'Manueller Anwesenheitseintrag');return $id;
 }
 private function audit(int $id,string $uid,string $action,string $by,?string $note):void{$this->insert('re_erp_attendance_audit',['attendance_id'=>$id,'user_id'=>$uid,'action'=>$action,'event_at'=>date('Y-m-d H:i:s'),'performed_by'=>$by,'note'=>$note]);}
 private function insert(string $table,array $data):int{$q=$this->db->getQueryBuilder();$q->insert($table)->values(array_map(fn($v)=>$q->createNamedParameter($v),$data))->executeStatement();return (int)$this->db->lastInsertId('*PREFIX*'.$table);}
 private function update(int $id,array $data):void{$q=$this->db->getQueryBuilder();$q->update('re_erp_attendance');foreach($data as $k=>$v)$q->set($k,$q->createNamedParameter($v));$q->where($q->expr()->eq('id',$q->createNamedParameter($id)))->executeStatement();}
}
