<?php
declare(strict_types=1);
namespace OCA\ReinhardtERP\Service;
use OCP\Files\File;
use OCP\Files\Folder;
use OCP\Files\IRootFolder;
use OCP\IUserSession;
final class FolderService {
 public function __construct(private IRootFolder $rootFolder,private IUserSession $userSession){}
 public function ensureCustomerFolder(string $customerNo,string $name):string{$root=$this->userRoot();$base=$this->folder($root,'ERP');$customers=$this->folder($base,'Kunden');$folderName=$this->safe(($customerNo!==''?$customerNo.'_':'').$name);$customer=$this->folder($customers,$folderName);foreach(['01_Kundendaten','02_Anfragen','03_Angebote','04_Auftraege','05_Projekte','06_Rechnungen','07_Korrespondenz','08_Bilder','09_Sonstiges'] as $sub)$this->folder($customer,$sub);return 'ERP/Kunden/'.$folderName;}
 public function ensureProjectFolder(string $customerPath,string $projectNo,string $title):string{$node=$this->folderByPath($customerPath);$projects=$this->folder($node,'05_Projekte');$folderName=$this->safe($projectNo.'_'.$title);$project=$this->folder($projects,$folderName);foreach(['01_Aufmass','02_Planung','03_Zeichnungen','04_Material','05_Bestellungen','06_Rapporte','07_Fotos','08_Abnahme','09_Rechnung'] as $sub)$this->folder($project,$sub);return trim($customerPath,'/').'/05_Projekte/'.$folderName;}
 public function ensureReportRoot(string $projectPath):string{$project=$this->folderByPath($projectPath);$this->folder($project,'06_Rapporte');return trim($projectPath,'/').'/06_Rapporte';}
 public function ensureBillingBatchFolder(string $customerPath,string $batchNo):string{$customer=$this->folderByPath($customerPath);$invoices=$this->folder($customer,'06_Rechnungen');$prep=$this->folder($invoices,'Abrechnungsvorbereitung');$name=$this->safe($batchNo);$this->folder($prep,$name);return trim($customerPath,'/').'/06_Rechnungen/Abrechnungsvorbereitung/'.$name;}
 public function ensureInvoiceFolder(string $customerPath,string $invoiceNo):string{$customer=$this->folderByPath($customerPath);$invoices=$this->folder($customer,'06_Rechnungen');$name=$this->safe($invoiceNo);$this->folder($invoices,$name);return trim($customerPath,'/').'/06_Rechnungen/'.$name;}
 public function ensureReportFolder(string $projectPath,string $reportNo,string $title):string{$project=$this->folderByPath($projectPath);$reports=$this->folder($project,'06_Rapporte');$name=$this->safe($reportNo.'_'.$title);$folder=$this->folder($reports,$name);$this->folder($folder,'Anhaenge');return trim($projectPath,'/').'/06_Rapporte/'.$name;}
 public function write(string $folderPath,string $name,string $content):string{$folder=$this->folderByPath($folderPath);$safe=$this->safeFile($name);try{$node=$folder->get($safe);if($node instanceof File){$node->putContent($content);}else{throw new \RuntimeException('Dateiname ist bereits ein Ordner.');}}catch(\OCP\Files\NotFoundException){$folder->newFile($safe,$content);}return trim($folderPath,'/').'/'.$safe;}
 public function writeFromLocalFile(string $folderPath,string $name,string $tmpPath):string{$content=file_get_contents($tmpPath);if($content===false)throw new \RuntimeException('Datei konnte nicht gelesen werden.');return $this->write($folderPath,$name,$content);}
 public function saveCompanyLogo(string $content,string $extension):string{$root=$this->userRoot();$erp=$this->folder($root,'ERP');$settings=$this->folder($erp,'Einstellungen');foreach(['Firmenlogo.png','Firmenlogo.jpg','Firmenlogo.jpeg'] as $old){try{$node=$settings->get($old);if($node instanceof File)$node->delete();}catch(\OCP\Files\NotFoundException){}}$ext=in_array(strtolower($extension),['png','jpg','jpeg'],true)?strtolower($extension):'png';return $this->write('ERP/Einstellungen','Firmenlogo.'.$ext,$content);}
 public function companyLogo():?array{foreach(['png'=>'image/png','jpg'=>'image/jpeg','jpeg'=>'image/jpeg'] as $ext=>$mime){try{$node=$this->folderByPath('ERP/Einstellungen')->get('Firmenlogo.'.$ext);if($node instanceof File)return ['content'=>$node->getContent(),'mime'=>$mime,'extension'=>$ext,'path'=>'ERP/Einstellungen/Firmenlogo.'.$ext];}catch(\Throwable){}}return null;}
 private function folderByPath(string $path):Folder{$node=$this->userRoot();foreach(explode('/',trim($path,'/')) as $part){if($part!=='')$node=$this->folder($node,$part);}if(!$node instanceof Folder)throw new \RuntimeException('Pfad ist kein Ordner.');return $node;}
 private function userRoot():Folder{$uid=$this->userSession->getUser()?->getUID();if($uid===null)throw new \RuntimeException('Kein angemeldeter Benutzer.');return $this->rootFolder->getUserFolder($uid);}
 private function folder($parent,string $name):Folder{try{$node=$parent->get($name);if(!$node instanceof Folder)throw new \RuntimeException('Ordnername ist bereits als Datei vorhanden: '.$name);return $node;}catch(\OCP\Files\NotFoundException){return $parent->newFolder($name);}}
 private function safe(string $value):string{$value=preg_replace('/[^\pL\pN._-]+/u','_',trim($value))??'Ordner';return trim($value,'._-')?:'Ordner';}
 private function safeFile(string $value):string{$value=preg_replace('/[^\pL\pN._ -]+/u','_',trim($value))??'Datei';return trim($value,'. ')?:'Datei';}
}
