<?php
declare(strict_types=1);
namespace OCA\ReinhardtERP\Migration;
use Closure;
use OCP\DB\ISchemaWrapper;
use OCP\Migration\IOutput;
use OCP\Migration\SimpleMigrationStep;
final class Version003500Date20260802233000 extends SimpleMigrationStep {
 public function changeSchema(IOutput $output, Closure $schemaClosure, array $options): ?ISchemaWrapper {
  $s=$schemaClosure();
  if(!$s->hasTable('re_erp_communications')){$t=$s->createTable('re_erp_communications');$t->addColumn('id','bigint',['autoincrement'=>true,'notnull'=>true]);$t->addColumn('customer_id','bigint',['notnull'=>true]);$t->addColumn('project_id','bigint',['notnull'=>false]);$t->addColumn('type','string',['length'=>32,'default'=>'note','notnull'=>true]);$t->addColumn('subject','string',['length'=>255,'notnull'=>true]);$t->addColumn('details','text',['notnull'=>false]);$t->addColumn('contact_at','datetime',['notnull'=>true]);$t->addColumn('follow_up_at','datetime',['notnull'=>false]);$t->addColumn('created_by','string',['length'=>64,'notnull'=>true]);$t->addColumn('created_at','datetime',['notnull'=>true]);$t->setPrimaryKey(['id']);$t->addIndex(['customer_id','contact_at'],'re_erp_comm_customer_date');$t->addIndex(['follow_up_at'],'re_erp_comm_followup');}
  if(!$s->hasTable('re_erp_offers')){$t=$s->createTable('re_erp_offers');$t->addColumn('id','bigint',['autoincrement'=>true,'notnull'=>true]);$t->addColumn('offer_no','string',['length'=>64,'notnull'=>true]);$t->addColumn('customer_id','bigint',['notnull'=>true]);$t->addColumn('project_id','bigint',['notnull'=>false]);$t->addColumn('title','string',['length'=>255,'notnull'=>true]);$t->addColumn('offer_date','date',['notnull'=>true]);$t->addColumn('valid_until','date',['notnull'=>false]);$t->addColumn('status','string',['length'=>32,'default'=>'draft','notnull'=>true]);$t->addColumn('notes','text',['notnull'=>false]);$t->addColumn('net_amount','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('vat_rate','decimal',['precision'=>5,'scale'=>2,'default'=>19,'notnull'=>true]);$t->addColumn('gross_amount','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('created_by','string',['length'=>64,'notnull'=>true]);$t->addColumn('created_at','datetime',['notnull'=>true]);$t->addColumn('updated_at','datetime',['notnull'=>true]);$t->setPrimaryKey(['id']);$t->addUniqueIndex(['offer_no'],'re_erp_offer_no');$t->addIndex(['customer_id','status'],'re_erp_offer_customer_status');}
  if(!$s->hasTable('re_erp_offer_items')){$t=$s->createTable('re_erp_offer_items');$t->addColumn('id','bigint',['autoincrement'=>true,'notnull'=>true]);$t->addColumn('offer_id','bigint',['notnull'=>true]);$t->addColumn('position_no','integer',['default'=>1,'notnull'=>true]);$t->addColumn('description','text',['notnull'=>true]);$t->addColumn('quantity','decimal',['precision'=>12,'scale'=>2,'default'=>1,'notnull'=>true]);$t->addColumn('unit','string',['length'=>32,'default'=>'Stk.','notnull'=>true]);$t->addColumn('unit_price','decimal',['precision'=>12,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('total_price','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->setPrimaryKey(['id']);$t->addIndex(['offer_id','position_no'],'re_erp_offer_item_offer');}
  if(!$s->hasTable('re_erp_orders')){$t=$s->createTable('re_erp_orders');$t->addColumn('id','bigint',['autoincrement'=>true,'notnull'=>true]);$t->addColumn('order_no','string',['length'=>64,'notnull'=>true]);$t->addColumn('offer_id','bigint',['notnull'=>false]);$t->addColumn('customer_id','bigint',['notnull'=>true]);$t->addColumn('project_id','bigint',['notnull'=>false]);$t->addColumn('title','string',['length'=>255,'notnull'=>true]);$t->addColumn('order_date','date',['notnull'=>true]);$t->addColumn('status','string',['length'=>32,'default'=>'open','notnull'=>true]);$t->addColumn('net_amount','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('gross_amount','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('created_by','string',['length'=>64,'notnull'=>true]);$t->addColumn('created_at','datetime',['notnull'=>true]);$t->addColumn('updated_at','datetime',['notnull'=>true]);$t->setPrimaryKey(['id']);$t->addUniqueIndex(['order_no'],'re_erp_order_no');$t->addIndex(['customer_id','status'],'re_erp_order_customer_status');}
  if(!$s->hasTable('re_erp_order_items')){$t=$s->createTable('re_erp_order_items');$t->addColumn('id','bigint',['autoincrement'=>true,'notnull'=>true]);$t->addColumn('order_id','bigint',['notnull'=>true]);$t->addColumn('position_no','integer',['default'=>1,'notnull'=>true]);$t->addColumn('description','text',['notnull'=>true]);$t->addColumn('quantity','decimal',['precision'=>12,'scale'=>2,'default'=>1,'notnull'=>true]);$t->addColumn('unit','string',['length'=>32,'default'=>'Stk.','notnull'=>true]);$t->addColumn('unit_price','decimal',['precision'=>12,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('total_price','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->setPrimaryKey(['id']);$t->addIndex(['order_id','position_no'],'re_erp_order_item_order');}
  if(!$s->hasTable('re_erp_stock_movements')){$t=$s->createTable('re_erp_stock_movements');$t->addColumn('id','bigint',['autoincrement'=>true,'notnull'=>true]);$t->addColumn('material_id','bigint',['notnull'=>true]);$t->addColumn('project_id','bigint',['notnull'=>false]);$t->addColumn('movement_type','string',['length'=>16,'notnull'=>true]);$t->addColumn('quantity','decimal',['precision'=>12,'scale'=>3,'notnull'=>true]);$t->addColumn('note','string',['length'=>255,'notnull'=>false]);$t->addColumn('created_by','string',['length'=>64,'notnull'=>true]);$t->addColumn('created_at','datetime',['notnull'=>true]);$t->setPrimaryKey(['id']);$t->addIndex(['material_id','created_at'],'re_erp_stock_material_date');}
  if($s->hasTable('re_erp_materials')){$t=$s->getTable('re_erp_materials');if(!$t->hasColumn('stock_quantity'))$t->addColumn('stock_quantity','decimal',['precision'=>12,'scale'=>3,'default'=>0,'notnull'=>true]);if(!$t->hasColumn('min_stock'))$t->addColumn('min_stock','decimal',['precision'=>12,'scale'=>3,'default'=>0,'notnull'=>true]);if(!$t->hasColumn('purchase_price'))$t->addColumn('purchase_price','decimal',['precision'=>12,'scale'=>2,'default'=>0,'notnull'=>true]);if(!$t->hasColumn('sale_price'))$t->addColumn('sale_price','decimal',['precision'=>12,'scale'=>2,'default'=>0,'notnull'=>true]);if(!$t->hasColumn('supplier'))$t->addColumn('supplier','string',['length'=>255,'notnull'=>false]);}
  return $s;
 }
}
