<?php
declare(strict_types=1);
namespace OCA\ReinhardtERP\Migration;
use Closure;use OCP\DB\ISchemaWrapper;use OCP\Migration\IOutput;use OCP\Migration\SimpleMigrationStep;
final class Version001300Date20260803120000 extends SimpleMigrationStep {
 public function changeSchema(IOutput $output,Closure $schemaClosure,array $options):?ISchemaWrapper{$s=$schemaClosure();
  if(!$s->hasTable('re_erp_invoices')){$t=$s->createTable('re_erp_invoices');$t->addColumn('id','bigint',['autoincrement'=>true,'notnull'=>true]);$t->addColumn('invoice_no','string',['length'=>64,'notnull'=>true]);$t->addColumn('customer_id','bigint',['notnull'=>true]);$t->addColumn('project_id','bigint',['notnull'=>false]);$t->addColumn('invoice_date','date',['notnull'=>true]);$t->addColumn('status','string',['length'=>24,'default'=>'draft','notnull'=>true]);$t->addColumn('net_amount','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('vat_rate','decimal',['precision'=>5,'scale'=>2,'default'=>19,'notnull'=>true]);$t->addColumn('gross_amount','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('folder_path','string',['length'=>1024,'notnull'=>false]);$t->addColumn('created_by','string',['length'=>64,'notnull'=>true]);$t->addColumn('created_at','datetime',['notnull'=>true]);$t->setPrimaryKey(['id']);$t->addUniqueIndex(['invoice_no'],'re_erp_invoice_no');$t->addIndex(['customer_id','project_id'],'re_erp_invoice_customer_project');}
  if(!$s->hasTable('re_erp_invoice_items')){$t=$s->createTable('re_erp_invoice_items');$t->addColumn('id','bigint',['autoincrement'=>true,'notnull'=>true]);$t->addColumn('invoice_id','bigint',['notnull'=>true]);$t->addColumn('source_type','string',['length'=>24,'default'=>'time','notnull'=>true]);$t->addColumn('source_id','bigint',['notnull'=>false]);$t->addColumn('description','text',['notnull'=>true]);$t->addColumn('quantity','decimal',['precision'=>12,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('unit','string',['length'=>32,'default'=>'Std.','notnull'=>true]);$t->addColumn('unit_price','decimal',['precision'=>12,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('total_price','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->setPrimaryKey(['id']);$t->addIndex(['invoice_id'],'re_erp_invoice_item_invoice');}
  if($s->hasTable('re_erp_workday_entries')){$t=$s->getTable('re_erp_workday_entries');if(!$t->hasColumn('invoice_id'))$t->addColumn('invoice_id','bigint',['notnull'=>false]);}
  return $s;}
}
