<?php
declare(strict_types=1);
namespace OCA\ReinhardtERP\Migration;
use Closure;use OCP\DB\ISchemaWrapper;use OCP\Migration\IOutput;use OCP\Migration\SimpleMigrationStep;
final class Version001400Date20260803140000 extends SimpleMigrationStep {
 public function changeSchema(IOutput $output,Closure $schemaClosure,array $options):?ISchemaWrapper{$s=$schemaClosure();
  if(!$s->hasTable('re_erp_billing_batches')){$t=$s->createTable('re_erp_billing_batches');$t->addColumn('id','bigint',['autoincrement'=>true,'notnull'=>true]);$t->addColumn('batch_no','string',['length'=>64,'notnull'=>true]);$t->addColumn('customer_id','bigint',['notnull'=>true]);$t->addColumn('project_id','bigint',['notnull'=>false]);$t->addColumn('title','string',['length'=>255,'notnull'=>true]);$t->addColumn('notes','text',['notnull'=>false]);$t->addColumn('total_hours','decimal',['precision'=>12,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('net_amount','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('folder_path','string',['length'=>1024,'notnull'=>false]);$t->addColumn('status','string',['length'=>24,'default'=>'prepared','notnull'=>true]);$t->addColumn('created_by','string',['length'=>64,'notnull'=>true]);$t->addColumn('created_at','datetime',['notnull'=>true]);$t->setPrimaryKey(['id']);$t->addUniqueIndex(['batch_no'],'re_erp_batch_no');$t->addIndex(['customer_id','project_id'],'re_erp_batch_customer_project');}
  if(!$s->hasTable('re_erp_billing_batch_items')){$t=$s->createTable('re_erp_billing_batch_items');$t->addColumn('id','bigint',['autoincrement'=>true,'notnull'=>true]);$t->addColumn('batch_id','bigint',['notnull'=>true]);$t->addColumn('entry_id','bigint',['notnull'=>true]);$t->addColumn('work_date','date',['notnull'=>true]);$t->addColumn('user_id','string',['length'=>64,'notnull'=>true]);$t->addColumn('activity','text',['notnull'=>true]);$t->addColumn('hours','decimal',['precision'=>8,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('hourly_rate','decimal',['precision'=>12,'scale'=>2,'default'=>0,'notnull'=>true]);$t->addColumn('amount','decimal',['precision'=>14,'scale'=>2,'default'=>0,'notnull'=>true]);$t->setPrimaryKey(['id']);$t->addIndex(['batch_id'],'re_erp_batch_item_batch');$t->addUniqueIndex(['batch_id','entry_id'],'re_erp_batch_item_unique');}
  if($s->hasTable('re_erp_workday_entries')){$t=$s->getTable('re_erp_workday_entries');if(!$t->hasColumn('billing_batch_id'))$t->addColumn('billing_batch_id','bigint',['notnull'=>false]);}
  return $s;}
}
