<?php require __DIR__.'/_nav.php'; ?>
<?php $url=$_['urlGenerator']; ?>
<div id="app-content"><main class="rel">
<section class="rel-head"><h1>Über Betrio & Release</h1><p>Administration, Versionsstand und Freigabe-Check für den produktiven Betrieb.</p><span class="rel-badge">Betrio <?php p($_['appVersion']); ?></span></section>
<div class="rel-grid">
<section class="rel-card"><h2>Produkt</h2><p><b>Betrio</b><br>ERP für Nextcloud mit mobiler Baustellenoberfläche.</p><p><b>Entwickler:</b> André Reinhardt</p><p><b>Version:</b> <?php p($_['appVersion']); ?></p><p><b>Status:</b> Aktuelle Version</p></section>
<section class="rel-card"><h2>Administration</h2><a class="rel-btn" href="<?php p($url->linkToRoute('reinhardterp.systemCheck.index')); ?>">Systemprüfung</a><a class="rel-btn alt" href="<?php p($url->linkToRoute('reinhardterp.module.users')); ?>">Benutzer & Rechte</a><a class="rel-btn alt" href="<?php p($url->linkToRoute('reinhardterp.business.mobileAdmin')); ?>">Mobile</a><a class="rel-btn alt" href="<?php p($url->linkToRoute('reinhardterp.business.documentation')); ?>">Dokumentation</a><a class="rel-btn alt" href="<?php p($url->linkToRoute('reinhardterp.business.privacy')); ?>">Datenschutz</a></section>
<section class="rel-card wide"><h2>Funktionstest</h2><p>Mit diesem Funktionstest können Administratoren die wichtigsten Bereiche nach Installation oder Update kontrollieren:</p><ol class="rel-list"><li>Installation/Update und Anmeldung</li><li>Administrator und Monteur prüfen</li><li>Kunde anlegen</li><li>Projekt anlegen und Monteur freigeben</li><li>Dokument und Projektfoto öffnen/erfassen</li><li>Arbeitszeit erfassen</li><li>Material entnehmen</li><li>Rapport erstellen und Inhalte kontrollieren</li><li>Kundenunterschrift speichern</li><li>Rapport/PDF kontrollieren</li><li>Mobile-PWA öffnen</li><li>Offline-Zeit und Offline-Material testen</li><li>Wieder online gehen und Sync auf genau eine Buchung prüfen</li><li>Projekt archivieren und Archiv kontrollieren</li></ol></section>
<section class="rel-card"><h2>Öffentliche Veröffentlichung</h2><ul class="rel-list"><li>Nextcloud App Store: Server-App vorbereiten</li><li>Google Play: Betrio Mobile nach Freigabe veröffentlichen</li><li>Apple App Store: anschließend vorgesehene Store-Version</li></ul><p>Store-Verfügbarkeit wird erst nach tatsächlicher Veröffentlichung als verfügbar gekennzeichnet.</p></section>
<section class="rel-card"><h2>Supportdiagnose</h2><p>Bei einem Fehler sollten mindestens Betrio-Version, Nextcloud-Version, betroffener Bereich, genaue Schritte, Fehlermeldung und bei Serverfehlern der relevante Nextcloud-Logauszug dokumentiert werden.</p><a class="rel-btn alt" href="<?php p($url->linkToRoute('reinhardterp.business.documentation')); ?>#support">Support-Leitfaden</a></section>
<section class="rel-card wide"><h2>Betrio unterstützen</h2><p>Betrio wird unabhängig entwickelt und als Open-Source-Software bereitgestellt. Wer die Weiterentwicklung freiwillig unterstützen möchte, kann dies über PayPal tun.</p><a class="rel-btn" href="https://paypal.me/betrio" target="_blank" rel="noopener noreferrer">Betrio über PayPal unterstützen</a><p class="erp-muted">Freiwillige Unterstützung ohne Gegenleistung. Keine steuerlich absetzbare Spende.</p></section>
<section class="rel-card wide"><h2>Funktionsübersicht</h2><p class="rel-ok">✓ Dokumentation integriert &nbsp; ✓ Mobile-Verwaltung &nbsp; ✓ PWA &nbsp; ✓ Offline-Basis &nbsp; ✓ Offline Zeit/Material Sync</p><p>Die technische Serverprüfung erfolgt bewusst dynamisch über <b>Verwaltung → Systemprüfung</b>, damit PHP-, Nextcloud-, Datenbank-, Dateisystem- und Serverzustand nicht nur statisch behauptet werden.</p></section>
</div></main></div>