<?php require __DIR__.'/_nav.php'; ?>
<?php $url=$_['urlGenerator']; ?>
<style>
.rel{max-width:1100px;margin:0 auto;padding:28px}.rel-head{padding:26px;border:1px solid #dfe6ef;border-radius:20px;background:#fff;margin-bottom:18px}.rel-head h1{margin:0;color:#0b1f55}.rel-badge{display:inline-block;margin-top:10px;padding:6px 10px;border-radius:999px;background:#fff4d6;color:#7a5000;font-weight:800}.rel-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.rel-card{border:1px solid #dfe6ef;border-radius:18px;background:#fff;padding:22px}.rel-card.wide{grid-column:1/-1}.rel-card h2{margin-top:0;color:#172554}.rel-list{line-height:1.7;color:#475569;padding-left:21px}.rel-btn{display:inline-block;padding:10px 14px;border-radius:10px;background:#1265d8;color:#fff!important;text-decoration:none;font-weight:700;margin:4px 5px 4px 0}.rel-btn.alt{background:#eef5ff;color:#1265d8!important}.rel-ok{color:#237333;font-weight:800}.rel-warn{padding:13px;border-radius:11px;background:#fff7e5;border-left:4px solid #d38a00}@media(max-width:800px){.rel{padding:16px}.rel-grid{grid-template-columns:1fr}.rel-card.wide{grid-column:auto}}
</style>
<div id="app-content"><main class="rel">
<section class="rel-head"><h1>Über NextERP & Release</h1><p>Administration, Versionsstand und Freigabe-Check für den produktiven Betrieb.</p><span class="rel-badge">NextERP 1.4.3</span></section>
<div class="rel-grid">
<section class="rel-card"><h2>Produkt</h2><p><b>NextERP</b><br>ERP für Nextcloud mit mobiler Baustellenoberfläche.</p><p><b>Entwickler:</b> André Reinhardt</p><p><b>Version:</b> 1.4.0</p><p><b>Status:</b> Aktuelle Version</p></section>
<section class="rel-card"><h2>Administration</h2><a class="rel-btn" href="<?php p($url->linkToRoute('reinhardterp.systemCheck.index')); ?>">Systemprüfung</a><a class="rel-btn alt" href="<?php p($url->linkToRoute('reinhardterp.module.users')); ?>">Benutzer & Rechte</a><a class="rel-btn alt" href="<?php p($url->linkToRoute('reinhardterp.business.mobileAdmin')); ?>">Mobile</a><a class="rel-btn alt" href="<?php p($url->linkToRoute('reinhardterp.business.documentation')); ?>">Dokumentation</a></section>
<section class="rel-card wide"><h2>Funktionstest</h2><p>Mit diesem Funktionstest können Administratoren die wichtigsten Bereiche nach Installation oder Update kontrollieren:</p><ol class="rel-list"><li>Installation/Update und Anmeldung</li><li>Administrator und Monteur prüfen</li><li>Kunde anlegen</li><li>Projekt anlegen und Monteur freigeben</li><li>Dokument und Projektfoto öffnen/erfassen</li><li>Arbeitszeit erfassen</li><li>Material entnehmen</li><li>Rapport erstellen und Inhalte kontrollieren</li><li>Kundenunterschrift speichern</li><li>Rapport/PDF kontrollieren</li><li>Mobile-PWA öffnen</li><li>Offline-Zeit und Offline-Material testen</li><li>Wieder online gehen und Sync auf genau eine Buchung prüfen</li><li>Projekt archivieren und Archiv kontrollieren</li></ol></section>
<section class="rel-card"><h2>Öffentliche Veröffentlichung</h2><ul class="rel-list"><li>Nextcloud App Store: Server-App vorbereiten</li><li>Google Play: NextERP Mobile nach Freigabe veröffentlichen</li><li>Apple App Store: anschließend vorgesehene Store-Version</li></ul><p>Store-Verfügbarkeit wird erst nach tatsächlicher Veröffentlichung als verfügbar gekennzeichnet.</p></section>
<section class="rel-card"><h2>Supportdiagnose</h2><p>Bei einem Fehler sollten mindestens NextERP-Version, Nextcloud-Version, betroffener Bereich, genaue Schritte, Fehlermeldung und bei Serverfehlern der relevante Nextcloud-Logauszug dokumentiert werden.</p><a class="rel-btn alt" href="<?php p($url->linkToRoute('reinhardterp.business.documentation')); ?>#support">Support-Leitfaden</a></section>
<section class="rel-card wide"><h2>Funktionsübersicht</h2><p class="rel-ok">✓ Dokumentation integriert &nbsp; ✓ Mobile-Verwaltung &nbsp; ✓ PWA &nbsp; ✓ Offline-Basis &nbsp; ✓ Offline Zeit/Material Sync</p><p>Die technische Serverprüfung erfolgt bewusst dynamisch über <b>Verwaltung → Systemprüfung</b>, damit PHP-, Nextcloud-, Datenbank-, Dateisystem- und Serverzustand nicht nur statisch behauptet werden.</p></section>
</div></main></div>