<?php
require __DIR__.'/_nav.php';
use OCP\IURLGenerator;
$url=\OC::$server->get(IURLGenerator::class);
$labels=['vacation'=>'Urlaub','sick'=>'Krankheit','training'=>'Schulung / Berufsschule','other'=>'Sonstige Abwesenheit'];
$statusLabels=['pending'=>'Beantragt','approved'=>'Genehmigt','rejected'=>'Abgelehnt'];
?>
<div id="app-content"><div class="erp-page"><div class="erp-head"><div><h1 class="erp-help-target" data-betrio-help="absence-time">Abwesenheiten</h1><p class="erp-sub">Urlaub, Krankheit, Schulung und sonstige Abwesenheiten verwalten. Genehmigte Abwesenheiten werden im Arbeitszeitkonto auf die Sollzeit angerechnet.</p></div></div>
<div class="erp-cards erp-time-summary"><?php foreach(($_['users']??[]) as $u): $v=$_['vacation'][$u['uid']]??['annual'=>30,'used'=>0,'remaining'=>30]; ?><div class="erp-card"><span><?php p(!empty($_['canManageTeam'])?$u['displayName']:'Mein Urlaub '.date('Y')); ?></span><strong><?php p(number_format((float)$v['remaining'],1,',','.')); ?> Tage</strong><small><?php p(number_format((float)$v['used'],1,',','.').' von '.number_format((float)$v['annual'],1,',','.').' Tagen genommen'); ?></small></div><?php endforeach; ?></div>
<div class="erp-card"><div class="erp-section-head"><div><h2><?php p(!empty($_['canManageTeam'])?'Abwesenheit erfassen':'Abwesenheit melden / Urlaub beantragen'); ?></h2><p class="erp-muted">Urlaubsanträge von Mitarbeitern benötigen eine Freigabe. Krankheit und andere Abwesenheiten werden erfasst; Details zur Erkrankung gehören nicht in Betrio.</p></div></div><form class="erp-form-card" method="post" action="<?php p($url->linkToRoute('reinhardterp.module.saveAbsence')); ?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']); ?>"><div class="erp-form-grid"><?php if(!empty($_['canManageTeam'])): ?><div><label>Mitarbeiter</label><select name="userId" required><?php foreach($_['users'] as $u): ?><option value="<?php p($u['uid']); ?>"><?php p($u['displayName'].' · '.$u['uid']); ?></option><?php endforeach; ?></select></div><?php endif; ?><div><label>Art</label><select name="type" required><option value="vacation">Urlaub</option><option value="sick">Krankheit</option><option value="training">Schulung / Berufsschule</option><option value="other">Sonstige Abwesenheit</option></select></div><div><label>Von</label><input type="date" name="dateFrom" required></div><div><label>Bis</label><input type="date" name="dateTo" required></div><div><label>Notiz</label><input type="text" name="note" placeholder="Optional, keine Gesundheitsdetails"></div></div><button class="button primary">Speichern</button></form></div>
<div class="erp-card"><div class="erp-section-head"><div><h2><?php p(!empty($_['canManageTeam'])?'Abwesenheiten im Team':'Meine Abwesenheiten'); ?></h2></div></div><div class="erp-table"><table><thead><tr><?php if(!empty($_['canManageTeam'])): ?><th>Mitarbeiter</th><?php endif; ?><th>Art</th><th>Zeitraum</th><th>Status</th><th>Notiz</th><?php if(!empty($_['canManageTeam'])): ?><th>Aktion</th><?php endif; ?></tr></thead><tbody><?php foreach(($_['rows']??[]) as $r): ?><tr><?php if(!empty($_['canManageTeam'])): ?><td><strong><?php p($r['display_name']); ?></strong></td><?php endif; ?><td><?php p($labels[$r['type']]??$r['type']); ?></td><td><?php p(date('d.m.Y',strtotime((string)$r['date_from'])).' – '.date('d.m.Y',strtotime((string)$r['date_to']))); ?></td><td><span class="erp-badge"><?php p($statusLabels[$r['status']]??$r['status']); ?></span></td><td><?php p($r['note']?:'—'); ?></td><?php if(!empty($_['canManageTeam'])): ?><td><?php if($r['status']==='pending'): ?><div class="erp-timer-actions"><form method="post" action="<?php p($url->linkToRoute('reinhardterp.module.updateAbsenceStatus',['id'=>$r['id']])); ?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']); ?>"><input type="hidden" name="status" value="approved"><button class="button primary">Genehmigen</button></form><form method="post" action="<?php p($url->linkToRoute('reinhardterp.module.updateAbsenceStatus',['id'=>$r['id']])); ?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']); ?>"><input type="hidden" name="status" value="rejected"><button class="button">Ablehnen</button></form></div><?php else: ?>—<?php endif; ?></td><?php endif; ?></tr><?php endforeach; ?><?php if(empty($_['rows'])): ?><tr><td colspan="6" class="erp-empty">Noch keine Abwesenheiten erfasst.</td></tr><?php endif; ?></tbody></table></div></div>
</div></div>
