<?php
$url=\OC::$server->get(\OCP\IURLGenerator::class);$activities=$_['activities']??[];
$labels=['file_created'=>'Neu','file_changed'=>'Geändert','file_moved'=>'Verschoben','file_deleted'=>'Gelöscht'];
?>
<div id="app-content"><div id="app-content-wrapper"><?php print_unescaped($this->inc('_nav'));?><main class="erp-main erp-file-activity-page">
<header class="erp-project-hero"><div><span class="erp-record-kicker">Nextcloud Dateien</span><h1>Dateiaktivitäten</h1><p class="erp-muted">Neue und geänderte Dateien in allen Betrio-Projekten – auch bei Upload über Nextcloud, Desktop-Sync oder WebDAV.</p></div></header>
<section class="erp-card erp-wide"><div class="erp-section-head"><div><h2>Letzte Aktivitäten</h2><p class="erp-muted">Die neuesten Dateiänderungen aus deinen freigegebenen Projekten.</p></div></div>
<?php if($activities):?><div class="erp-file-activity-toolbar" aria-label="Dateiaktivitäten filtern"><button type="button" class="erp-file-activity-filter is-active" data-action="all">Alle</button><button type="button" class="erp-file-activity-filter" data-action="file_created">Neu</button><button type="button" class="erp-file-activity-filter" data-action="file_changed">Geändert</button><button type="button" class="erp-file-activity-filter" data-action="file_moved">Verschoben</button><button type="button" class="erp-file-activity-filter" data-action="file_deleted">Gelöscht</button></div><?php endif;?>
<?php if(!$activities):?><p class="erp-muted">Noch keine Dateiaktivitäten erfasst. Neue Änderungen werden ab diesem Update protokolliert.</p><?php else:?><div class="erp-file-activity-list">
<?php foreach($activities as $a):?><a class="erp-file-activity-row" data-action="<?php p((string)($a['action']??''));?>" href="<?php p($url->linkToRoute('reinhardterp.page.projectExplorer',['id'=>(int)$a['project_id']]));?>"><span class="erp-file-activity-badge"><?php p($labels[$a['action']]??'Datei');?></span><span><strong><?php p(($a['project_no']??'').' · '.($a['project_title']??''));?></strong><small><?php p((string)($a['details']??''));?></small></span><span class="erp-file-activity-meta"><?php p((string)($a['display_name']??$a['created_by']??''));?><br><?php p(date('d.m.Y H:i',strtotime((string)$a['created_at'])));?></span></a><?php endforeach;?></div><div class="erp-file-activity-empty-filter" hidden>Keine Aktivitäten für diesen Filter vorhanden.</div><?php endif;?></section><script>(function(){const buttons=[...document.querySelectorAll('.erp-file-activity-filter')],rows=[...document.querySelectorAll('.erp-file-activity-row')],empty=document.querySelector('.erp-file-activity-empty-filter');buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');const action=b.dataset.action;let visible=0;rows.forEach(r=>{const show=action==='all'||r.dataset.action===action;r.hidden=!show;if(show)visible++;});if(empty)empty.hidden=visible!==0;}));})();</script></main></div></div>
