<?php require __DIR__.'/_nav.php'; $url=\OC::$server->get(\OCP\IURLGenerator::class); ?>
<div id="app-content"><div class="erp-page erp-finance-page">
<div class="erp-head"><div><span class="erp-eyebrow">FINANZEN · BANKUMSÄTZE</span><h1>Bankumsätze</h1><p class="erp-sub">Kontoumsätze per CSV importieren und Zahlungseingänge vorhandenen Rechnungen zuordnen.</p></div></div>
<?php if(!empty($_['message'])):?><div class="erp-notice success"><?php p($_['message']);?></div><?php endif;?>
<?php if(!empty($_['error'])):?><div class="erp-notice error"><?php p($_['error']);?></div><?php endif;?>
<section class="erp-card erp-wide"><div class="erp-section-head"><div><h2>Bankkonto</h2><p class="erp-muted">Lege das Konto einmal an. Es werden keine Online-Banking-Zugangsdaten benötigt oder gespeichert.</p></div></div>
<?php if(empty($_['accounts'])):?><form method="post" action="<?php p($url->linkToRoute('reinhardterp.document.bankAccountAdd'));?>" class="erp-form-grid"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><div><label>Kontobezeichnung</label><input name="name" placeholder="z. B. Geschäftskonto" required></div><div><label>Bank</label><input name="bankName" placeholder="z. B. Kasseler Sparkasse"></div><div><label>IBAN</label><input name="iban" autocomplete="off"></div><div><label>BIC</label><input name="bic" autocomplete="off"></div><div><label>&nbsp;</label><button class="button primary">Bankkonto anlegen</button></div></form><?php else:?>
<?php foreach($_['accounts'] as $a):?><div class="erp-list-row"><span><strong><?php p($a['name']);?></strong><small><?php p(($a['bank_name']??'').(!empty($a['iban'])?' · '.$a['iban']:''));?></small></span><em>CSV-Import</em></div><?php endforeach;?><?php endif;?></section>
<section class="erp-card erp-wide"><div class="erp-section-head"><div><h2>CSV importieren</h2><p class="erp-muted">CSV aus dem Online-Banking exportieren und hier einlesen. Bereits importierte Umsätze werden anhand ihrer Daten erkannt und nicht doppelt angelegt.</p></div></div>
<?php if(empty($_['accounts'])):?><p class="erp-muted">Bitte zuerst oben ein Bankkonto anlegen.</p><?php else:?><form method="post" enctype="multipart/form-data" action="<?php p($url->linkToRoute('reinhardterp.document.bankImport'));?>" class="erp-form-grid"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><div><label>Bankkonto</label><select name="accountId" required><?php foreach($_['accounts'] as $a):?><option value="<?php p((string)$a['id']);?>"><?php p($a['name']);?></option><?php endforeach;?></select></div><div><label>CSV-Datei</label><input type="file" name="bankFile" accept=".csv,text/csv" required></div><div><label>&nbsp;</label><button class="button primary">Umsätze importieren</button></div></form><p class="erp-muted">Erkannt werden unter anderem Buchungstag/Buchungsdatum, Betrag, Verwendungszweck, Name des Auftraggebers oder Empfängers und IBAN. Semikolon und Komma als Trennzeichen werden unterstützt.</p><?php endif;?></section>
<section class="erp-card erp-wide"><h2>Bankbewegungen</h2><?php if(empty($_['transactions'])):?><p class="erp-muted">Noch keine Bankumsätze importiert.</p><?php else:?><div class="erp-material-stream"><?php foreach($_['transactions'] as $t):?><article><span><strong><?php p(date('d.m.Y',strtotime($t['booking_date'])).' · '.($t['counterparty']?:'Bankumsatz'));?></strong><small><?php p($t['purpose']??'');?><?php if(!empty($t['invoice_no'])):?> · Vorschlag: <?php p($t['invoice_no']);?><?php endif;?></small></span><em><?php p(number_format((float)$t['amount'],2,',','.').' €');?></em><?php if(($t['match_status']??'')==='suggested'&&!empty($t['invoice_id'])):?><form method="post" action="<?php p($url->linkToRoute('reinhardterp.document.bankMatch',['id'=>$t['id']]));?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><input type="hidden" name="invoiceId" value="<?php p($t['invoice_id']);?>"><button class="button primary">Zahlung übernehmen</button></form><?php elseif(($t['match_status']??'')==='booked'):?><span class="erp-badge">Gebucht</span><?php endif;?></article><?php endforeach;?></div><?php endif;?></section>
</div></div>
