<?php
require __DIR__.'/_nav.php';
use OCP\IURLGenerator;
$url=\OC::$server->get(IURLGenerator::class);
script('reinhardterp','inventory');
$materials=$_['materials'];
$total=count($materials);
$low=count(array_filter($materials,fn($m)=>(float)($m['stock_quantity']??0)>0 && (float)($m['stock_quantity']??0)<=(float)($m['min_stock']??0)));
$out=count(array_filter($materials,fn($m)=>(float)($m['stock_quantity']??0)<=0));
$value=array_sum(array_map(fn($m)=>(float)($m['stock_quantity']??0)*(float)($m['purchase_price']??0),$materials));
?>
<div id="app-content"><div class="erp-page erp-inventory-page">
<div class="erp-page-head"><div><h1>Lagerübersicht</h1><p class="erp-sub">Bestände im Blick behalten und Lagerbewegungen schnell buchen.</p></div><div class="erp-head-actions"><a class="button" href="<?php p($url->linkToRoute('reinhardterp.business.inventoryPdf'));?>" target="_blank">Inventurliste PDF</a><a class="button" href="<?php p($url->linkToRoute('reinhardterp.business.inventoryPrint'));?>" target="_blank">Drucken</a><a class="button primary" href="<?php p($url->linkToRoute('reinhardterp.business.inventoryAssistant'));?>">Inventur-Assistent</a><button class="button" type="button" id="datanorm-open">DATANORM importieren</button><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.materials'));?>">Materialstamm</a></div></div>
<?php if((string)($_GET['datanorm']??'')==='1'):?><div class="erp-info-banner">DATANORM-Import abgeschlossen: <?php p((int)($_GET['created']??0));?> neu, <?php p((int)($_GET['updated']??0));?> aktualisiert, <?php p((int)($_GET['skipped']??0));?> übersprungen.</div><?php endif;?>
<?php if((string)($_GET['inventoryCount']??'')==='1'):?><div class="erp-info-banner">Inventur abgeschlossen: <?php p((int)($_GET['changed']??0));?> Bestände korrigiert, <?php p((int)($_GET['unchanged']??0));?> unverändert.</div><?php endif;?>
<div class="erp-modal-backdrop" id="datanorm-modal" hidden><section class="erp-modal-card"><div class="erp-modal-head"><div><h2>DATANORM importieren</h2><p>DATANORM 4/5 Artikelstammdaten prüfen und anschließend in den Materialstamm übernehmen.</p></div><button type="button" class="button" id="datanorm-close">Schließen</button></div><form id="datanorm-form" method="post" enctype="multipart/form-data" action="<?php p($url->linkToRoute('reinhardterp.business.datanormImport'));?>" data-preview-url="<?php p($url->linkToRoute('reinhardterp.business.datanormPreview'));?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><label>Lieferant<select id="datanorm-supplier" name="supplierId" required><option value="">Lieferant auswählen …</option><?php foreach(($_['suppliers']??[]) as $supplier):?><option value="<?php p($supplier['id']);?>"><?php p($supplier['name']);?></option><?php endforeach;?></select></label><label>DATANORM-Datei<input type="file" id="datanorm-file" name="datanorm" accept=".001,.002,.003,.004,.005,.dat,.txt" required></label><div class="erp-datanorm-actions"><button type="button" class="button" id="datanorm-preview">Datei prüfen</button><button type="submit" class="button primary" id="datanorm-import" disabled>Import bestätigen</button></div><div id="datanorm-result" class="erp-datanorm-result" hidden></div></form></section></div>
<div class="erp-material-summary">
<button class="erp-stat inventory-filter active" data-filter=""><span>Artikel im Lager</span><strong><?php p($total);?></strong></button>
<button class="erp-stat inventory-filter" data-filter="low"><span>Unter Mindestbestand</span><strong><?php p($low);?></strong></button>
<button class="erp-stat inventory-filter" data-filter="out"><span>Nicht auf Lager</span><strong><?php p($out);?></strong></button>
<div class="erp-stat"><span>Lagerwert EK</span><strong><?php p(number_format($value,2,',','.').' €');?></strong></div>
</div>
<div class="erp-inventory-workspace">
<div class="erp-inventory-toolbar"><div class="erp-inventory-search-wrap"><input id="inventory-search" type="search" placeholder="Artikel, Bezeichnung, Lieferant …"></div><select id="inventory-supplier-filter"><option value="">Alle Lieferanten</option><?php foreach(($_['suppliers']??[]) as $supplier):?><option value="<?php p((string)$supplier['id']);?>"><?php p($supplier['name']);?></option><?php endforeach;?></select><select id="inventory-sort"><option value="name">Bezeichnung A–Z</option><option value="supplier">Lieferant A–Z</option><option value="article">Artikelnummer</option><option value="stock-asc">Bestand aufsteigend</option><option value="stock-desc">Bestand absteigend</option></select><span class="erp-inventory-count" id="inventory-result-count"><?php p($total);?> Treffer</span></div>
<div class="erp-table"><table><thead><tr><th>Artikel</th><th>Bezeichnung</th><th>Gruppe</th><th>Lagerort</th><th>Bestand</th><th>Minimum</th><th>Bestellmenge</th><th>Lieferant</th><th>Status</th></tr></thead><tbody id="inventory-table-body">
<?php foreach($materials as $m):$stock=(float)($m['stock_quantity']??0);$min=(float)($m['min_stock']??0);$state=$stock<=0?'out':($stock<=$min?'low':'ok');$search=mb_strtolower(implode(' ',[$m['article_no']??'',$m['name']??'',$m['group_name']??$m['material_group']??'',$m['supplier_name']??$m['supplier']??'',$m['storage_location']??'']));?>
<tr data-search="<?php p($search);?>" data-stock="<?php p($state);?>" data-supplier-id="<?php p((string)($m['supplier_id']??''));?>" data-supplier="<?php p(mb_strtolower((string)($m['supplier_name']??'')));?>" data-name="<?php p(mb_strtolower((string)($m['name']??'')));?>" data-article="<?php p(mb_strtolower((string)($m['article_no']??'')));?>" data-stock-value="<?php p((string)$stock);?>"><td><div class="erp-inventory-article"><strong><?php p($m['article_no']??'');?></strong><?php if(!empty($m['barcode'])):?><small><?php p($m['barcode']);?></small><?php endif;?></div></td><td><strong><?php p($m['name']);?></strong></td><td><?php p($m['group_name']??$m['material_group']??'—');?></td><td><?php p($m['storage_location']??'—');?></td><td><span class="erp-stock-number stock-<?php p($state);?>"><?php p(number_format($stock,3,',','.').' '.($m['unit']??''));?></span></td><td><?php p(number_format($min,3,',','.'));?></td><td><?php p(number_format((float)($m['reorder_quantity']??0),3,',','.'));?></td><td><?php p($m['supplier_name']??$m['supplier']??'—');?></td><td><span class="erp-stock-badge erp-stock-<?php p($state);?>"><?php p($state==='out'?'Leer':($state==='low'?'Nachbestellen':'OK'));?></span></td></tr><?php endforeach;?></tbody></table><div id="inventory-empty" class="erp-empty" hidden>Kein Material für diese Auswahl gefunden.</div></div>
</div>
<div class="erp-inventory-actions">
<section class="erp-inventory-card"><div class="erp-inventory-card-head"><h2>Lagerbewegung buchen</h2><p>Zugang, Entnahme oder Bestandskorrektur direkt erfassen.</p></div><form class="erp-inventory-movement-form" method="post" action="<?php p($url->linkToRoute('reinhardterp.business.saveStockMovement'));?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><div class="erp-form-grid"><div class="erp-span-2"><label>Material suchen</label><input id="movement-material-search" type="search"><label>Material</label><select id="movement-material-select" name="materialId" required><?php foreach($materials as $m):?><option value="<?php p($m['id']);?>" data-search="<?php p(mb_strtolower(($m['article_no']??'').' '.$m['name'].' '.($m['barcode']??'')));?>" data-ek="<?php p(number_format((float)($m['purchase_price']??$m['price']??0),2,'.',''));?>" data-vk="<?php p(number_format((float)($m['sale_price']??$m['price']??0),2,'.',''));?>"><?php p(($m['article_no']??'').' · '.$m['name'].' · '.number_format((float)($m['stock_quantity']??0),3,',','.').' '.($m['unit']??''));?></option><?php endforeach;?></select></div><div><label>Bewegung</label><select id="movement-type" name="movementType"><option value="in">Zugang</option><option value="out">Entnahme</option><option value="adjustment">Bestandskorrektur</option></select></div><div><label>Menge / neuer Bestand</label><input type="number" step="0.001" name="quantity" required></div><div class="erp-stock-price-field"><label>EK netto</label><input id="movement-purchase-price" type="number" step="0.01" min="0" name="purchasePrice"></div><div class="erp-stock-price-field"><label>VK-Aufschlag %</label><input id="movement-sale-markup" type="number" step="0.01" min="0" name="saleMarkupPercent"><small id="movement-sale-preview" class="erp-muted">VK wird aus EK + Aufschlag berechnet.</small></div><div><label>Projekt</label><select name="projectId"><option value="">ohne Projekt</option><?php foreach($_['projects'] as $p):?><option value="<?php p($p['id']);?>"><?php p($p['project_no'].' · '.$p['title']);?></option><?php endforeach;?></select></div><div><label>Notiz</label><input name="note"></div></div><button class="button primary">Lagerbewegung buchen</button></form></section>
<details class="erp-inventory-card erp-movement-history"><summary>Letzte Lagerbewegungen</summary><div class="erp-table"><table><thead><tr><th>Zeitpunkt</th><th>Material</th><th>Bewegung</th><th>Menge</th><th>Projekt</th><th>Notiz</th></tr></thead><tbody><?php foreach($_['movements'] as $m):$labels=['in'=>'Zugang','out'=>'Entnahme','adjustment'=>'Korrektur'];?><tr><td><?php p(date('d.m.Y H:i',strtotime($m['created_at'])));?></td><td><?php p(($m['article_no']??'').' · '.$m['material_name']);?></td><td><span class="erp-movement-type <?php p($m['movement_type']);?>"><?php p($labels[$m['movement_type']]??$m['movement_type']);?></span></td><td><?php p(number_format((float)$m['quantity'],3,',','.').' '.$m['unit']);?></td><td><?php p($m['project_no']?:'—');?></td><td><?php p($m['note']);?></td></tr><?php endforeach;?></tbody></table></div></details>
</div></div></div>
