<?php require __DIR__.'/_nav.php'; use OCP\IURLGenerator; $url=\OC::$server->get(IURLGenerator::class); $f=$_['filters']; ?>
<div id="app-content"><div class="erp-page">
<div class="erp-head"><div><h1>Abrechnung vorbereiten</h1><p class="erp-sub">Vorgemerkte Arbeitszeiten bündeln und als wieder aufrufbare Abrechnungsliste speichern. Hier wird noch keine Rechnung erzeugt.</p></div><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.timeEvaluation',['billingStatus'=>'reserved']));?>">Vorgemerkte Zeiten prüfen</a></div>
<?php if(!empty($_['message'])):?><div class="erp-notice erp-notice-<?php p($_['messageType']);?>"><?php p($_['message']);?></div><?php endif;?>
<div class="erp-status-board"><div><strong>1. Offen</strong><span>Noch prüfen</span></div><div class="active"><strong>2. Vorgemerkt</strong><span>Für Abrechnung auswählbar</span></div><div><strong>3. Abrechnungspaket</strong><span>Gespeichert und später wieder aufrufbar</span></div></div>
<?php if($_['batches']):?><div class="erp-card"><h2>Gespeicherte Abrechnungspakete</h2><div class="erp-table"><table><thead><tr><th>Nummer</th><th>Datum</th><th>Kunde</th><th>Projekt</th><th>Stunden</th><th>Arbeitswert netto</th><th></th></tr></thead><tbody><?php foreach($_['batches'] as $b):?><tr><td><strong><?php p($b['batch_no']);?></strong></td><td><?php p(date('d.m.Y',strtotime($b['created_at'])));?></td><td><?php p(($b['customer_no']??'').' '.($b['customer_name']??''));?></td><td><?php p(($b['project_no']??'').' '.($b['project_title']??''));?></td><td><?php p(number_format((float)$b['total_hours'],2,',','.'));?> h</td><td><?php p(number_format((float)$b['net_amount'],2,',','.'));?> €</td><td><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.billingBatchDetail',['id'=>$b['id']]));?>">Öffnen</a></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?>
<form method="get" action="<?php p($url->linkToRoute('reinhardterp.module.invoicePreparation'));?>" class="erp-form-card"><div class="erp-form-grid"><div><label>Kunde</label><select name="customerId"><option value="">Alle Kunden</option><?php foreach($_['customers'] as $c):?><option value="<?php p($c['id']);?>" <?php if((int)$f['customerId']===(int)$c['id'])echo 'selected';?>><?php p(($c['customer_no']??'').' '.$c['name']);?></option><?php endforeach;?></select></div><div><label>Projekt</label><select name="projectId"><option value="">Alle Projekte</option><?php foreach($_['projects'] as $p):?><option value="<?php p($p['id']);?>" <?php if((int)$f['projectId']===(int)$p['id'])echo 'selected';?>><?php p(($p['project_no']??'').' '.$p['title']);?></option><?php endforeach;?></select></div></div><div class="erp-actions"><button class="primary">Auswahl anzeigen</button></div></form>
<?php if($_['groups']):?><div class="erp-three-col"><?php foreach($_['groups'] as $g):?><div class="erp-card"><span><?php p($g['customer']);?></span><strong><?php p($g['project']);?></strong><p><?php p($g['count']);?> Einträge · <?php p(number_format($g['hours'],2,',','.'));?> Std.</p><p><b><?php p(number_format($g['amount'],2,',','.'));?> € Arbeitswert netto</b></p></div><?php endforeach;?></div><?php endif;?>
<form id="erp-batch-form" method="post" action="<?php p($url->linkToRoute('reinhardterp.module.createBillingBatch'));?>" class="erp-form-card"><input type="hidden" name="requesttoken" value="<?php p($requestToken);?>">
<div class="erp-form-grid"><div><label>Bezeichnung</label><input name="title" value="Abrechnungsvorbereitung" required></div><div><label>Interne Notiz</label><input name="notes" placeholder="z. B. Teilabrechnung Montage"></div></div>
<div class="erp-table"><table><thead><tr><th><input type="checkbox" onclick="document.querySelectorAll('.batch-check').forEach(c=>c.checked=this.checked)"></th><th>Datum</th><th>Kunde</th><th>Projekt</th><th>Mitarbeiter</th><th>Tätigkeit</th><th>Std.</th><th>Satz</th><th>Arbeitswert</th></tr></thead><tbody><?php foreach($_['rows'] as $r):?><tr><td><input class="batch-check" type="checkbox" name="entryIds[]" value="<?php p($r['id']);?>"></td><td><?php p(date('d.m.Y',strtotime($r['work_date'])));?></td><td><?php p(($r['customer_no']??'').' '.($r['customer_name']??''));?></td><td><?php p(($r['project_no']??'').' '.($r['project_title']??''));?></td><td><?php p($r['user_display_name']);?></td><td class="erp-activity"><?php p($r['activity']);?></td><td><?php p(number_format((float)$r['hours'],2,',','.'));?></td><td><?php p(number_format((float)$r['effective_rate'],2,',','.'));?> €</td><td><?php p(number_format((float)$r['amount'],2,',','.'));?> €</td></tr><?php endforeach;?><?php if(!$_['rows']):?><tr><td colspan="9" class="erp-empty">Keine vorgemerkten Zeiten vorhanden. In der Zeitauswertung zuerst Zeiten vormerken.</td></tr><?php endif;?></tbody></table></div>
<div class="erp-actions"><button class="primary" type="submit">Abrechnungspaket speichern</button><small>Nur Zeiten desselben Kunden und Projekts gemeinsam auswählen. Es wird ausdrücklich keine Rechnung erzeugt.</small></div></form>
</div></div><script>document.getElementById('erp-batch-form')?.addEventListener('submit',e=>{if(!document.querySelector('.batch-check:checked')){e.preventDefault();alert('Bitte mindestens einen vorgemerkten Zeiteintrag auswählen.')}});</script>
