<?php
require __DIR__.'/_document_master.php';
$i=$_['invoice'];$items=$_['items']??[];$project=$_['project']??null;$draft=$i['status']==='draft';$type=$i['invoice_type']??'invoice';
$labels=['invoice'=>'Rechnung','advance'=>'Abschlagsrechnung','final'=>'Schlussrechnung','credit'=>'Gutschrift'];$title=$labels[$type]??'Rechnung';
$payable=(float)$i['gross_amount']-($type==='final'?(float)($i['advance_gross_amount']??0):0);
?><!doctype html><html><head><meta charset="utf-8"><title><?php p($title.' '.($draft?'Entwurf':$i['invoice_no']));?></title></head><body><div class="doc">
<header class="doc-head"><div><?php if($logo):?><img class="doc-logo" src="<?php p($logo);?>"><?php else:?><strong><?php p($company['name']??'');?></strong><?php endif;?></div><div class="doc-company"><strong><?php p($company['name']??'');?></strong><br><?php p($company['street']??'');?><br><?php p(trim(($company['zip']??'').' '.($company['city']??'')));?><?php if(!empty($company['phone'])):?><br>Telefon: <?php p($company['phone']);?><?php endif;?><?php if(!empty($company['email'])):?><br>Mail: <?php p($company['email']);?><?php endif;?><?php if(!empty($company['website'])):?><br>Web: <?php p($company['website']);?><?php endif;?><?php foreach([1,2] as $b):if(!empty($company['bank'.$b.'_name'])):?><div class="doc-bank"><strong>Bankverbindung</strong><?php p($company['bank'.$b.'_name']);?><br>IBAN <?php p($company['bank'.$b.'_iban']??'');?><br>BIC <?php p($company['bank'.$b.'_bic']??'');?></div><?php endif;endforeach;?></div></header>
<section class="doc-recipient-wrap"><div><div class="doc-senderline"><?php p(erpCompanyLine($company));?></div><div class="doc-recipient"><?php echo erpAddr($customer);?></div></div><div class="doc-meta"><div class="doc-meta-row"><span>Sachbearbeiter/-in:</span><strong><?php p($i['clerk_name']??$company['owner']??'');?></strong></div><div class="doc-meta-row"><span>Datum:</span><strong><?php p(date('d.m.Y',strtotime((string)$i['invoice_date'])));?></strong></div><div class="doc-meta-row"><span><?php p($title);?>-Nr.:</span><strong><?php p($draft?'wird bei Finalisierung vergeben':$i['invoice_no']);?></strong></div><?php if(!empty($i['service_date'])):?><div class="doc-meta-row"><span>Leistungsdatum:</span><strong><?php p(date('d.m.Y',strtotime((string)$i['service_date'])));?></strong></div><?php endif;?><?php if(!empty($i['due_date'])):?><div class="doc-meta-row"><span>Fällig:</span><strong><?php p(date('d.m.Y',strtotime((string)$i['due_date'])));?></strong></div><?php endif;?></div></section>
<h1 class="doc-title"><?php p($draft?$title.' – Entwurf':$title);?></h1>
<table class="doc-table"><thead><tr><th class="p">Pos.</th><th class="q">Anzahl</th><th class="u">Einheit</th><th>Bezeichnung</th><th class="price">Einzelpreis</th><th class="total">Gesamtpreis</th></tr></thead><tbody><?php foreach($items as $n=>$x):?><tr><td><?php p($n+1);?></td><td class="q"><?php p(number_format((float)$x['quantity'],2,',','.'));?></td><td><?php p($x['unit']);?></td><td class="doc-desc"><?php if(!empty($x['is_alternative'])):?><div class="doc-alt">Alternativposition</div><?php endif;?><?php echo (string)$x['description'];?></td><td class="price"><?php p(number_format((float)$x['unit_price'],2,',','.'));?> €</td><td class="total"><?php p(number_format((float)$x['total_price'],2,',','.'));?> €</td></tr><?php endforeach;?></tbody></table>
<div class="doc-totals"><div class="doc-total-row"><span>Summe</span><strong><?php p(number_format((float)$i['net_amount'],2,',','.'));?> €</strong></div><div class="doc-total-row"><span>Mehrwertsteuer <?php p(number_format((float)$i['vat_rate'],0,',','.'));?>%</span><span><?php p(number_format((float)$i['gross_amount']-(float)$i['net_amount'],2,',','.'));?> €</span></div><div class="doc-total-row doc-total-grand"><span>Gesamtbetrag</span><span><?php p(number_format((float)$i['gross_amount'],2,',','.'));?> €</span></div><?php if($type==='final'&&(float)($i['advance_gross_amount']??0)>0):?><div class="doc-total-row"><span>abzgl. Abschläge</span><span>- <?php p(number_format((float)$i['advance_gross_amount'],2,',','.'));?> €</span></div><div class="doc-total-row doc-total-grand"><span>Verbleibender Zahlbetrag</span><span><?php p(number_format($payable,2,',','.'));?> €</span></div><?php endif;?></div>
<?php if(!empty($i['notes'])):?><div class="doc-notes"><?php echo (string)$i['notes'];?></div><?php endif;?>
<footer class="doc-footer"><div><?php p($company['name']??'');?><br><?php p($company['street']??'');?><br><?php p(trim(($company['zip']??'').' '.($company['city']??'')));?></div><div><?php if(!empty($company['taxNo'])):?>St.-Nr. <?php p($company['taxNo']);?><br><?php endif;?><?php if(!empty($company['vatId'])):?>USt-IdNr. <?php p($company['vatId']);?><?php endif;?></div><div><?php p($company['email']??'');?><br><?php p($company['website']??'');?></div></footer>
</div><script>window.print()</script></body></html>
