<?php require __DIR__.'/_mobile_pwa.php'; ?>
<?php $url=$_['urlGenerator'];$p=$_['project']; ?><style>
.erp-rm{max-width:720px;margin:0 auto;padding:16px 14px 90px;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;color:#14213d}.erp-rm *{box-sizing:border-box}.erp-rm a{text-decoration:none}.erp-rh{display:flex;gap:12px;align-items:center;margin-bottom:17px}.erp-rback{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;background:#e8f3fa;color:#1265d8;font-size:26px}.erp-rh h1{margin:0;font-size:23px;color:#0b1f55}.erp-rh p{margin:2px 0;color:#6b7280;font-size:13px}.erp-rcard{display:block;border:1px solid #dfe5ec;border-radius:17px;background:#fff;padding:14px;margin:9px 0;color:#14213d!important}.erp-rcard small{display:block;color:#1265d8;font-weight:800;font-size:11px}.erp-rcard b{display:block;font-size:16px;margin:3px 0}.erp-rmeta{color:#6b7280;font-size:12px}.erp-rstatus{display:inline-block;margin-top:7px;padding:4px 8px;border-radius:999px;background:#eef3f8;font-size:11px;font-weight:700}.erp-rsection{margin:20px 0}.erp-rsection h2{font-size:18px;margin:0 0 8px}.erp-rline{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid #e5e7eb;font-size:13px}.erp-signbox{border:1px solid #dfe5ec;border-radius:18px;padding:14px;background:#fff}.erp-signbox label{display:block;font-size:13px;font-weight:700;margin:8px 0 5px}.erp-signbox input{width:100%;min-height:46px;border:1px solid #cfd7e3;border-radius:12px;padding:10px;font:inherit}.erp-signcanvas{width:100%;height:210px;border:2px dashed #b9c5d3;border-radius:14px;background:#fff;touch-action:none;display:block}.erp-signactions{display:grid;grid-template-columns:1fr 2fr;gap:9px;margin-top:10px}.erp-signactions button{min-height:48px;border-radius:13px;border:1px solid #cfd7e3;background:#fff;font-weight:800}.erp-signactions .primary{background:#1265d8;color:#fff;border-color:#1265d8}.erp-signed{padding:15px;border-radius:15px;background:#edf8f1;color:#196b37;font-weight:700}
</style>
<div id="app-content"><main class="erp-rm"><header class="erp-rh"><a class="erp-rback" href="<?php p($url->linkToRoute('reinhardterp.business.mobileProject',['id'=>(int)$p['id']])); ?>">‹</a><div><h1>Rapporte</h1><p><?php p(($p['project_no']??'').' · '.($p['title']??'')); ?></p></div></header>
<?php if(!$_['reports']):?><div class="erp-rcard">Für dieses Projekt sind keine offenen Rapporte vorhanden.</div><?php endif;?>
<?php foreach($_['reports'] as $r):?><a class="erp-rcard" href="<?php p($url->linkToRoute('reinhardterp.business.mobileReport',['id'=>(int)$r['id']])); ?>"><small><?php p($r['report_no']??'RAPPORT');?></small><b><?php p($r['title']??'Rapport');?></b><div class="erp-rmeta"><?php p($r['report_date']??'');?></div><span class="erp-rstatus"><?php p($r['status']??'Entwurf');?></span></a><?php endforeach;?>
</main></div>
<?php $mobileActive='projects'; $mobileProjectId=(int)($p['id']??0); require __DIR__.'/_mobile_nav.php'; ?>
