<?php require __DIR__.'/_mobile_pwa.php'; ?>
<?php $url=$_['urlGenerator'];$selected=(int)($_['projectId']??0); ?><style>
.erp-mob2{max-width:720px;margin:0 auto;padding:16px 14px 96px;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;color:#14213d}.erp-mob2 *{box-sizing:border-box}.erp-mob2 a{text-decoration:none}.erp-mob2-head{display:flex;align-items:center;gap:12px;margin-bottom:18px}.erp-mob2-back{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;background:#e8f3fa;color:#1265d8;font-size:26px}.erp-mob2-head h1{margin:0;font-size:23px;color:#0b1f55}.erp-mob2-head p{margin:3px 0 0;color:#6b7280;font-size:13px}.erp-mob2-card{border:1px solid #dfe5ec;border-radius:18px;background:#fff;padding:15px;margin:10px 0}.erp-mob2-projectno{font-size:12px;font-weight:800;color:#1265d8}.erp-mob2-card h2{margin:4px 0 7px;font-size:20px}.erp-mob2-muted{color:#6b7280;font-size:13px}.erp-mob2-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.erp-mob2-action{min-height:92px;border:1px solid #dfe5ec;border-radius:17px;padding:14px;display:flex;flex-direction:column;justify-content:center;gap:5px;color:#14213d!important;background:#fff}.erp-mob2-action b{font-size:16px}.erp-mob2-action small{color:#6b7280}.erp-mob2-action.primary{background:#1265d8;color:#fff!important;border-color:#1265d8}.erp-mob2-action.primary small{color:#eaf3ff}.erp-mob2-form label{display:block;font-size:13px;font-weight:700;margin:13px 0 5px}.erp-mob2-form input,.erp-mob2-form select,.erp-mob2-form textarea{width:100%;min-height:46px;border:1px solid #cfd7e3;border-radius:12px;padding:10px 12px;background:#fff;color:#14213d;font:inherit}.erp-mob2-form textarea{min-height:100px;resize:vertical}.erp-mob2-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.erp-mob2-save{width:100%;min-height:52px;border:0;border-radius:14px;background:#1265d8;color:#fff;font-size:16px;font-weight:800;margin-top:18px}.erp-mob2-note{font-size:12px;color:#6b7280;margin-top:8px}@media(max-width:430px){.erp-mob2-grid,.erp-mob2-row{grid-template-columns:1fr 1fr}.erp-mob2{padding-left:12px;padding-right:12px}}
</style>
<div id="app-content"><main class="erp-mob2">
<header class="erp-mob2-head"><a class="erp-mob2-back" href="<?php p($url->linkToRoute('reinhardterp.business.mobile')); ?>">‹</a><div><h1>Zeit erfassen</h1><p>Schnell und manuell buchen</p></div></header>
<form class="erp-mob2-card erp-mob2-form" data-nexterp-offline="time" method="post" action="<?php p($url->linkToRoute('reinhardterp.business.saveMobileTime')); ?>">
<input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']??''); ?>">
<label>Projekt</label><select name="projectId" required><option value="">Projekt auswählen</option><?php foreach($_['projects'] as $p):?><option value="<?php p((string)$p['id']); ?>" <?php if((int)$p['id']===$selected)print_unescaped('selected');?>><?php p(trim(($p['project_no']??'').' · '.($p['title']??'')));?></option><?php endforeach;?></select>
<label>Datum</label><input type="date" name="workDate" value="<?php p(date('Y-m-d')); ?>" required>
<div class="erp-mob2-row"><div><label>Von</label><input type="time" name="startTime"></div><div><label>Bis</label><input type="time" name="endTime"></div></div>
<div class="erp-mob2-row"><div><label>Pause (Min.)</label><input type="number" name="breakMinutes" min="0" value="0"></div><div><label>Stunden</label><input type="number" name="hours" min="0" step="0.25" placeholder="z. B. 7,5"></div></div>
<label>Tätigkeit</label><textarea name="activity" required placeholder="Was wurde gemacht?"></textarea>
<label>Notiz</label><textarea name="notes" placeholder="Optional"></textarea>
<button class="erp-mob2-save" type="submit">Zeit speichern</button><div class="erp-mob2-note">Wenn Von/Bis ausgefüllt sind, kann Betrio die Stunden abzüglich Pause berechnen.</div>
</form></main></div>
<?php $mobileActive='time'; $mobileProjectId=(int)($_['projectId']??0); require __DIR__.'/_mobile_nav.php'; ?>
