<?php
declare(strict_types=1);
/** @var array $_ */
$url = $_['urlGenerator'] ?? \OC::$server->get(\OCP\IURLGenerator::class);
?>
<?php include __DIR__.'/_nav.php'; ?>
<main id="app-content"><div class="erp-page erp-privacy-page">
<section class="erp-doc-hero"><span class="erp-doc-chip">NextERP 1.4.5</span><h1>Datenschutz & Datenverarbeitung</h1><p>Technische Datenschutzinformationen für Administratoren und Betreiber von NextERP. Diese Seite beschreibt die Datenverarbeitung der Software und unterstützt bei der eigenen Datenschutzdokumentation.</p></section>
<div class="erp-privacy-notice"><strong>Wichtig:</strong> Der Betreiber der jeweiligen Nextcloud-Instanz ist für seine konkrete Nutzung, Rechtsgrundlagen, Informationspflichten, Aufbewahrungsfristen und Löschkonzepte verantwortlich. Diese technische Dokumentation ersetzt keine individuelle rechtliche Prüfung.</div>
<section class="erp-doc-section"><h2>Grundprinzip</h2><p>NextERP wird innerhalb der jeweiligen Nextcloud-Installation betrieben. Geschäftsdaten werden in der Nextcloud-Umgebung des Betreibers verarbeitet. NextERP benötigt für den normalen ERP-Betrieb keinen zentralen NextERP-Cloud-Dienst des Entwicklers.</p><p>Ob zusätzliche Datenübermittlungen stattfinden, hängt von der Konfiguration der Nextcloud und von zusätzlich installierten oder angebundenen Diensten ab. Diese müssen vom Betreiber separat bewertet werden.</p></section>
<section class="erp-doc-section"><h2>Verarbeitete Datenkategorien</h2><table class="erp-privacy-table"><thead><tr><th>Bereich</th><th>Typische Daten</th><th>Zweck</th></tr></thead><tbody>
<tr><td>Benutzer & Mitarbeiter</td><td>Benutzerkennung, Anzeigename, Rollen, Rechte, Projektfreigaben</td><td>Anmeldung, Berechtigung, Nachvollziehbarkeit</td></tr>
<tr><td>Kunden & Kontakte</td><td>Name/Firma, Anschrift, Telefon, E-Mail, Ansprechpartner</td><td>Kunden- und Auftragsbearbeitung</td></tr>
<tr><td>Projekte & Kommunikation</td><td>Projektangaben, Notizen, Termine, Kommunikation</td><td>Projektabwicklung und Dokumentation</td></tr>
<tr><td>Zeit & Material</td><td>Mitarbeiter, Arbeitszeit, Tätigkeit, Materialbuchungen</td><td>Leistungserfassung, Kalkulation und Abrechnung</td></tr>
<tr><td>Rapporte</td><td>Leistungen, Zeiten, Material, Freitext, Kundenunterschrift</td><td>Leistungsnachweis und Geschäftsabwicklung</td></tr>
<tr><td>Dokumente & Fotos</td><td>Projektdateien, Belege, Baustellen-/Dokumentationsfotos</td><td>Projektakte und Nachweis</td></tr>
<tr><td>Mobile Nutzung</td><td>Sitzungs-/Zugriffsdaten, lokale Offline-Daten soweit verwendet</td><td>Mobile Nutzung und Synchronisation</td></tr>
</tbody></table></section>
<section class="erp-doc-section"><h2>Speicherorte & Übertragung</h2><ul><li>ERP-Strukturdaten werden in der Datenbank der Nextcloud-Installation gespeichert.</li><li>Dateien und Dokumente werden innerhalb der vom Betreiber verwendeten Nextcloud-Dateiumgebung verarbeitet.</li><li>Mobile Geräte kommunizieren mit der vom Benutzer bzw. Betreiber verwendeten Nextcloud-Instanz.</li><li>Für produktive und mobile Nutzung sollte ausschließlich HTTPS eingesetzt werden.</li></ul></section>
<section class="erp-doc-section"><h2>Rollen & Zugriffsschutz</h2><p>Personenbezogene Daten dürfen nur Benutzern zugänglich sein, die sie für ihre Aufgaben benötigen. NextERP unterstützt Rollen, Rechte und Projektfreigaben. Jeder Mitarbeiter sollte ein eigenes Nextcloud-Konto verwenden. Gemeinsame Konten erschweren Nachvollziehbarkeit und Widerruf von Zugriffsrechten.</p></section>
<section class="erp-doc-section"><h2>Mobile Geräte & Offline-Daten</h2><p>Bei mobiler Nutzung können betriebliche Daten auf dem Endgerät angezeigt und – bei Offline-Funktionen – vorübergehend lokal vorgehalten werden. Firmenhandys sollten deshalb durch Gerätesperre geschützt sein. Bei Verlust eines Geräts sind Benutzerzugriff und aktive Sitzungen unverzüglich zu prüfen bzw. zu sperren.</p></section>
<section class="erp-doc-section"><h2>Aufbewahrung, Löschung & Betroffenenrechte</h2><p>NextERP legt keine allgemeingültigen gesetzlichen Löschfristen für den Betreiber fest. Der Betreiber muss für seine Datenarten passende Aufbewahrungs- und Löschregeln definieren und dabei handels-, steuer-, arbeits- und datenschutzrechtliche Anforderungen berücksichtigen. Löschungen dürfen nicht im Widerspruch zu gesetzlichen Aufbewahrungspflichten erfolgen.</p><p>Für Auskunft, Berichtigung, Löschung, Einschränkung oder Datenübertragbarkeit muss der Betreiber berücksichtigen, dass Informationen sowohl in NextERP-Datensätzen als auch in Nextcloud-Dateien, Kontakten, Kalendern, Sicherungen oder angebundenen Diensten vorkommen können.</p></section>
<section class="erp-doc-section"><h2>Backups & Protokolle</h2><p>Backups können personenbezogene Daten enthalten und müssen deshalb ebenfalls geschützt, zugriffsbeschränkt und in das Lösch-/Aufbewahrungskonzept einbezogen werden. Nextcloud-Protokolle können technische Benutzer-, IP- oder Zugriffsinformationen enthalten; deren Aufbewahrung richtet sich nach der Konfiguration des Betreibers.</p></section>
<section class="erp-doc-section"><h2>Externe Dienste & Erweiterungen</h2><p>NextERP kann in einer Umgebung betrieben werden, in der weitere Nextcloud-Apps, E-Mail-Dienste, Karten, externe Speicher, Push-Dienste oder andere Integrationen verwendet werden. Solche Dienste sind nicht automatisch Bestandteil dieser NextERP-Datenschutzbeschreibung und müssen vom Betreiber gesondert dokumentiert werden.</p></section>
<section class="erp-doc-section"><h2>Hinweise für App-Stores</h2><p>Für eine Veröffentlichung der mobilen Anwendung in App-Stores müssen die dort verlangten Angaben zur Datennutzung mit dem tatsächlichen Verhalten der jeweiligen App-Version übereinstimmen. Eine öffentlich erreichbare Datenschutzerklärung des App-Anbieters kann zusätzlich erforderlich sein. Diese In-App-Seite dient als technische Grundlage, ersetzt aber nicht automatisch die externe Store-Datenschutzerklärung.</p></section>
<section class="erp-doc-section"><h2>Checkliste für Betreiber</h2><ol><li>Verantwortlichen und Datenschutzkontakt in der eigenen Datenschutzerklärung benennen.</li><li>Zwecke und Rechtsgrundlagen der betrieblichen Verarbeitung festlegen.</li><li>Rollen und Projektzugriffe nach dem Minimalprinzip vergeben.</li><li>HTTPS, sichere Passwörter und Nextcloud-Sicherheitsfunktionen verwenden.</li><li>Aufbewahrungs- und Löschkonzept für Kunden-, Mitarbeiter-, Projekt- und Belegdaten festlegen.</li><li>Backups, Protokolle und mobile Endgeräte berücksichtigen.</li><li>Externe Dienste und Auftragsverarbeiter dokumentieren.</li><li>Bei Store-Veröffentlichung die Store-Datenschutzangaben separat prüfen.</li></ol></section>
<section class="erp-doc-section"><h2>Für Administratoren</h2><p>Technische Auffälligkeiten sollten zuerst unter <b>Verwaltung → Systemprüfung</b> kontrolliert werden. Die Benutzer- und Projektberechtigungen befinden sich unter <b>Verwaltung → Benutzer & Rechte</b>.</p></section>
</div></main></div>
