<?php
style('reinhardterp','style'); script('reinhardterp','project'); script('reinhardterp','project_permissions');
$url=\OC::$server->get(\OCP\IURLGenerator::class); $projectPath=trim((string)($project['folder_path']??''),'/'); $filesBase=$url->linkToRoute('files.view.index');
$folderUrl=static fn(string $path):string=>$filesBase.'?dir='.rawurlencode('/'.trim($path,'/'));
$fileUrl=static function(string $path)use($filesBase):string{$path=trim($path,'/');return $filesBase.'?dir='.rawurlencode(dirname('/'.$path)).'&scrollto='.rawurlencode(basename($path));};
$formatSize=static function(int $b):string{if($b<1024)return $b.' B';if($b<1048576)return number_format($b/1024,1,',','.').' KB';return number_format($b/1048576,1,',','.').' MB';};
$totalHours=array_sum(array_map(static fn($x)=>(float)$x['hours'],$times)); $statuses=['Anfrage','Angebot','Auftrag','Fertigung','Montage','Abnahme','Abrechnung','Abgeschlossen'];
$currentStatus=(string)($project['status']??'Anfrage');$idx=array_search(strtolower($currentStatus),array_map('strtolower',$statuses),true);$progress=$idx===false?0:(int)round(($idx/(count($statuses)-1))*100);
$cockpit=$cockpit??[];$projectCosts=$projectCosts??[];$offers=$offers??[];$orders=$orders??[];$projectEvents=$projectEvents??[];$documentRecords=$documentRecords??[];
$money=static fn($v):string=>number_format((float)$v,2,',','.').' €';
$memberMap=[];foreach(($projectMembers??[]) as $m)$memberMap[(string)$m['user_id']]=$m;
$openProjectFile=static fn(string $path):string=>$url->linkToRoute('reinhardterp.page.projectFile',['id'=>$project['id'],'path'=>$path]);
$folderLabels=['00_Eingang'=>'Eingang','01_Aufmass'=>'Aufmaß','02_Planung'=>'Planung','03_Zeichnungen'=>'Zeichnungen','04_Material'=>'Material','05_Bestellungen'=>'Bestellungen','06_Rapporte'=>'Rapporte','07_Fotos'=>'Fotos','08_Abnahme'=>'Abnahme','09_Rechnung'=>'Rechnung','10_Angebote'=>'Angebote','11_Auftraege'=>'Aufträge','12_Sonstiges'=>'Sonstiges'];
?>
<div id="app-content"><div id="app-content-wrapper"><?php print_unescaped($this->inc('_nav')); ?><main class="erp-main erp-project-center">
<header class="erp-project-hero"><div class="erp-project-identity"><span class="erp-record-kicker">Digitale Projektakte · <?=p($project['project_no'])?></span><h1><?=p($project['title'])?></h1><p><a href="<?=p($url->linkToRoute('reinhardterp.page.customerDetail',['id'=>$project['customer_id']]))?>"><?=p($project['customer_no'].' '.$project['customer_name'])?></a> · <strong><?=p($currentStatus)?></strong></p><div class="erp-project-progress"><i style="width:<?=p($progress)?>%"></i></div></div><div class="erp-project-hero-actions"><?php if($projectPath!==''):?><a class="button primary" href="<?=p($url->linkToRoute('reinhardterp.page.projectExplorer',['id'=>$project['id']]))?>"><span class="erp-ui-icon erp-icon-folder"></span>Projektordner</a><?php endif;?><?php if($projectPath!==''&&!empty($isProjectSupervisor)):?><a class="button" target="_blank" rel="noopener" href="<?=p($folderUrl($projectPath))?>">In Nextcloud öffnen</a><?php endif;?><a class="button" href="<?=p($url->linkToRoute('reinhardterp.module.reports',['projectId'=>$project['id']]))?>">+ Rapport</a><a class="button" href="<?=p($url->linkToRoute('reinhardterp.module.workdays'))?>">+ Zeit</a><?php if(!empty($isProjectSupervisor)):?><a class="button" href="<?=p($url->linkToRoute('reinhardterp.page.projectForm',['id'=>$project['id']]))?>">Bearbeiten</a><?php endif;?></div></header>
<nav class="erp-project-center-nav" aria-label="Projektcenter"><a href="#permissions">Freigaben</a><a href="#overview">Übersicht</a><?php if(!empty($isProjectSupervisor)):?><a href="#commercial">Angebote & Aufträge</a><?php endif;?><a href="#appointments">Termine</a><a href="#reports">Rapporte</a><a href="#time">Zeiten</a><a href="#material">Material</a><a href="#photos">Fotos</a><a href="#documents">Dokumente</a><?php if(!empty($isProjectSupervisor)):?><a href="#costs">Kosten</a><?php endif;?><a href="#timeline">Timeline</a></nav>
<section id="overview" class="erp-project-center-metrics"><article><span>Fortschritt</span><strong><?=p($progress)?> %</strong><small><?=p($currentStatus)?></small></article><article><span>Arbeitszeit</span><strong><?=p(number_format($totalHours,2,',','.'))?> h</strong><small><?=count($times)?> Buchungen</small></article><article><span>Rapporte</span><strong><?=count($reports)?></strong><small><?=count(array_filter($reports,static fn($r)=>empty($r['locked'])))?> offen</small></article><article><span>Projektwert</span><strong><?=p($money($projectCosts['projectValue']??0))?></strong><small><?=($projectCosts['orderValue']??0)>0?'Aufträge':'Angebote'?></small></article><article><span>Dokumente</span><strong><?=count($documents)?></strong><small><?=count($documentRecords)?> klassifiziert</small></article></section>
<section class="erp-card erp-permissions-compact" id="permissions"><div class="erp-permission-summary"><div><h2>Mitarbeiter & Freigaben</h2><?php if(!empty($canManageAssignments)):?><?php $assignedSummaries=[];foreach(($assignmentUsers??[]) as $u){$uid=(string)$u['uid'];if(isset($memberMap[$uid])){$folders=$memberMap[$uid]['folders']??[];$assignedSummaries[]=(string)$u['displayName'].' · '.count($folders).' Ordner';}}?><p class="erp-muted"><?php p(!empty($assignedSummaries)?implode(' · ',$assignedSummaries):'Noch keinem Monteur zugewiesen.'); ?></p><?php else:?><p class="erp-muted">Deine Projektfreigaben</p><?php endif;?></div><?php if(!empty($canManageAssignments)):?><button type="button" class="button erp-permission-toggle" aria-expanded="false" aria-controls="erp-permission-editor">Bearbeiten</button><?php endif;?></div>
<?php if(!empty($canManageAssignments)):?>
<div id="erp-permission-editor" class="erp-permission-editor" hidden><p class="erp-muted">Monteure sehen nur zugewiesene Projekte und die hier freigegebenen Projektordner.</p><form method="post" action="<?=p($url->linkToRoute('reinhardterp.project.saveAssignments',['id'=>$project['id']]))?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><div class="erp-permission-list">
<?php if(empty($assignmentUsers)):?><p class="erp-muted">Keine aktiven Monteure/Mitarbeiter vorhanden.</p><?php else:?><?php foreach($assignmentUsers as $u):$uid=(string)$u['uid'];$member=$memberMap[$uid]??null;$selected=$member!==null;$memberFolders=$member['folders']??\OCA\ReinhardtERP\Service\PermissionService::EMPLOYEE_DEFAULT_FOLDERS;?>
<article class="erp-permission-user"><label><input type="checkbox" name="projectUsers[]" value="<?=p($uid)?>" <?=$selected?'checked':''?>> <strong><?=p($u['displayName'])?></strong> <small><?=p($u['role'])?></small></label><div class="erp-folder-permissions"><?php foreach($folderLabels as $folder=>$label):?><label><input type="checkbox" name="folders[<?=p($uid)?>][]" value="<?=p($folder)?>" <?=in_array($folder,$memberFolders,true)?'checked':''?>> <?=p($label)?></label><?php endforeach;?></div></article>
<?php endforeach;?><?php endif;?></div><button class="button primary">Freigaben speichern</button></form></div>
<?php else:?><div class="erp-folder-summary"><strong>Für dich freigegebene Ordner:</strong> <?php foreach(($allowedProjectFolders??[]) as $folder):?><span class="erp-status-pill"><?=p($folderLabels[$folder]??$folder)?></span><?php endforeach;?></div><?php endif;?></section>
<?php if(!empty($isProjectSupervisor)):?><section class="erp-card erp-workflow-card"><div class="erp-section-head"><div><h2>Projektablauf</h2><p class="erp-muted">Der aktuelle Status steuert den Projektfortschritt.</p></div></div><div class="erp-workflow"><?php foreach($statuses as $status):?><form method="post" action="<?=p($url->linkToRoute('reinhardterp.project.updateStatus',['id'=>$project['id']]))?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><input type="hidden" name="status" value="<?=p($status)?>"><button class="erp-workflow-step <?=strcasecmp($currentStatus,$status)===0?'is-active':''?>"><span></span><?=p($status)?></button></form><?php endforeach;?></div></section><?php endif;?>
<div class="erp-project-center-grid">
<?php if(!empty($isProjectSupervisor)):?><section class="erp-card" id="commercial"><div class="erp-section-head"><div><h2>Angebote & Aufträge</h2><p class="erp-muted">Kaufmännische Dokumente direkt am Projekt.</p></div><div class="erp-actions"><a class="button" href="<?=p($url->linkToRoute('reinhardterp.business.offers'))?>">Angebot anlegen</a><a class="button" href="<?=p($url->linkToRoute('reinhardterp.business.orders'))?>">Aufträge</a></div></div><div class="erp-commercial-columns"><div><h3>Angebote</h3><?php if(!$offers):?><p class="erp-muted">Noch kein Angebot zugeordnet.</p><?php else:?><?php foreach($offers as $x):?><a class="erp-business-row" href="<?=p($url->linkToRoute('reinhardterp.business.offerDetail',['id'=>$x['id']]))?>"><span><strong><?=p($x['offer_no'])?></strong><small><?=p($x['title'])?></small></span><em><?=p($money($x['gross_amount']))?></em></a><?php endforeach;?><?php endif;?></div><div><h3>Aufträge</h3><?php if(!$orders):?><p class="erp-muted">Noch kein Auftrag zugeordnet.</p><?php else:?><?php foreach($orders as $x):?><a class="erp-business-row" href="<?=p($url->linkToRoute('reinhardterp.business.orderDetail',['id'=>$x['id']]))?>"><span><strong><?=p($x['order_no'])?></strong><small><?=p($x['title'])?></small></span><em><?=p($money($x['gross_amount']))?></em></a><?php endforeach;?><?php endif;?></div></div></section><?php endif;?>
<section class="erp-card" id="appointments"><div class="erp-section-head"><div><h2>Termine</h2><p class="erp-muted">Projektbezogene Termine aus dem Teamkalender.</p></div><a class="button" href="<?=p($url->linkToRoute('reinhardterp.module.teamEvents'))?>">Kalender öffnen</a></div><?php if(!$projectEvents):?><p class="erp-muted">Noch keine Termine diesem Projekt zugeordnet.</p><?php else:?><div class="erp-event-list"><?php foreach($projectEvents as $event):?><article><time><?=p(date('d.m.Y H:i',strtotime((string)$event['start_at'])))?></time><span><strong><?=p($event['title'])?></strong><small><?=p($event['location']??'')?></small></span></article><?php endforeach;?></div><?php endif;?></section>
</div>
<div class="erp-project-center-grid">
<section class="erp-card" id="reports"><div class="erp-section-head"><div><h2>Rapporte</h2><p class="erp-muted">Leistungsnachweise, Unterschriften und PDF.</p></div><a class="button primary" href="<?=p($url->linkToRoute('reinhardterp.module.reports',['projectId'=>$project['id']]))?>">+ Neuer Rapport</a></div><?php if(!$reports):?><p class="erp-muted">Noch keine Rapporte.</p><?php else:?><div class="erp-compact-list"><?php foreach(array_slice($reports,0,8) as $x):?><a href="<?=p($url->linkToRoute('reinhardterp.module.reportDetail',['id'=>$x['id']]))?>"><span><strong><?=p($x['report_no'])?></strong><small><?=p($x['title'])?> · <?=p($x['report_date'])?></small></span><em><?=p($x['status'])?></em></a><?php endforeach;?></div><?php endif;?></section>
<section class="erp-card" id="time"><div class="erp-section-head"><div><h2>Zeiterfassung</h2><p class="erp-muted">Letzte Arbeiten im Projekt.</p></div><a class="button" href="<?=p($url->linkToRoute('reinhardterp.module.workdays'))?>">Zeit buchen</a></div><?php if(!$times):?><p class="erp-muted">Noch keine Zeiten.</p><?php else:?><div class="erp-compact-table"><div class="erp-compact-table-head"><span>Datum</span><span>Mitarbeiter</span><span>Std.</span><span>Tätigkeit</span></div><?php foreach(array_slice($times,0,10) as $x):?><div><span><?=p($x['work_date'])?></span><span><?=p($x['user_id'])?></span><strong><?=p(number_format((float)$x['hours'],2,',','.'))?></strong><span><?=p($x['activity'])?></span></div><?php endforeach;?></div><?php endif;?></section>
</div>
<div class="erp-project-center-grid">
<section class="erp-card" id="material"><div class="erp-section-head"><div><h2>Material</h2><p class="erp-muted">In Rapporten erfasster Projektverbrauch.</p></div><a class="button" href="<?=p($url->linkToRoute('reinhardterp.module.materials'))?>">Materialstamm</a></div><?php if(!$projectMaterials):?><p class="erp-muted">Noch kein Material erfasst.</p><?php else:?><div class="erp-material-stream"><?php foreach($projectMaterials as $item):?><article><span><strong><?=p($item['description'])?></strong><small><?=p($item['report_no'])?> · <?=p(date('d.m.Y',strtotime((string)$item['report_date'])))?></small></span><em><?=p(number_format((float)$item['quantity'],3,',','.'))?> <?=p($item['unit']??'')?></em></article><?php endforeach;?></div><?php endif;?></section>
<section class="erp-card" id="photos"><div class="erp-section-head"><div><h2>Fotos</h2><p class="erp-muted">Bilder aus der digitalen Projektakte.</p></div><?php if($projectPath!==''&&!empty($isProjectSupervisor)):?><a class="button" target="_blank" rel="noopener" href="<?=p($folderUrl($projectPath.'/07_Fotos'))?>">Fotoordner</a><?php endif;?></div><?php if(empty($cockpit['photos'])):?><p class="erp-muted">Noch keine Bilder.</p><?php else:?><div class="erp-photo-strip"><?php foreach($cockpit['photos'] as $photo):?><a target="_blank" rel="noopener" href="<?=p($openProjectFile($photo['path']))?>"><span>🖼️</span><strong><?=p($photo['name'])?></strong><small><?=p(date('d.m.Y',(int)$photo['mtime']))?></small></a><?php endforeach;?></div><?php endif;?></section>
</div>
<section class="erp-card erp-document-center" id="documents"><div class="erp-section-head"><div><h2>Dokumenteingang</h2><p class="erp-muted">PDF, Angebot, Auftrag, Rechnung, Zeichnung oder Foto direkt dem Projekt zuordnen.</p></div><?php if($projectPath!==''&&!empty($isProjectSupervisor)):?><a class="button" target="_blank" rel="noopener" href="<?=p($folderUrl($projectPath))?>">Alle Dateien</a><?php endif;?></div><?php if($projectPath!==''):?><form class="erp-document-intake" method="post" enctype="multipart/form-data" action="<?=p($url->linkToRoute('reinhardterp.page.uploadProjectDocument',['id'=>$project['id']]))?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx,.dwg,.dxf" required><select name="documentType"><?php $uploadTypes=['inbox'=>['00_Eingang','Ungeprüfter Eingang'],'offer'=>['10_Angebote','Angebot'],'order'=>['11_Auftraege','Auftrag'],'invoice'=>['09_Rechnung','Rechnung'],'report'=>['06_Rapporte','Rapport'],'drawing'=>['03_Zeichnungen','Zeichnung'],'photo'=>['07_Fotos','Foto'],'material'=>['04_Material','Material'],'other'=>['12_Sonstiges','Sonstiges']];foreach($uploadTypes as $key=>$meta):if(!empty($isProjectSupervisor)||in_array($meta[0],$allowedProjectFolders??[],true)):?><option value="<?=p($key)?>"><?=p($meta[1])?></option><?php endif;endforeach;?></select><button class="button primary">Dem Projekt zuordnen</button></form><?php endif;?><?php if(!$documents):?><p class="erp-muted">Noch keine Projektdateien.</p><?php else:?><div class="erp-document-list"><?php foreach(array_slice($documents,0,16) as $doc):?><a class="erp-document-row" target="_blank" rel="noopener" href="<?=p($openProjectFile($doc['path']))?>"><span class="erp-file-icon"><?=str_starts_with((string)$doc['mime'],'image/')?'🖼️':((string)$doc['mime']==='application/pdf'?'📄':'📎')?></span><span class="erp-file-main"><strong><?=p($doc['name'])?></strong><small><?=p(str_replace($projectPath.'/','',$doc['path']))?></small></span><span class="erp-file-meta"><?=p($formatSize((int)$doc['size']))?><br><?=p(date('d.m.Y H:i',(int)$doc['mtime']))?></span><span class="button">Öffnen</span></a><?php endforeach;?></div><?php endif;?></section>
<?php if(!empty($isProjectSupervisor)):?><section class="erp-card erp-cost-center" id="costs"><div class="erp-section-head"><div><h2>Projektkosten & Leistung</h2><p class="erp-muted">Aktuelle Werte aus Auftrag/Angebot, Zeit und Rapportmaterial.</p></div></div><div class="erp-cost-grid"><article><span>Projektwert</span><strong><?=p($money($projectCosts['projectValue']??0))?></strong></article><article><span>Arbeitswert</span><strong><?=p($money($projectCosts['laborValue']??0))?></strong><small><?=p(number_format((float)($projectCosts['hours']??0),2,',','.'))?> h</small></article><article><span>Materialwert</span><strong><?=p($money($projectCosts['materialValue']??0))?></strong></article><article class="<?=($projectCosts['remaining']??0)<0?'is-negative':'is-positive'?>"><span>Rest / Deckung</span><strong><?=p($money($projectCosts['remaining']??0))?></strong><small>vor Fremdleistungen und Gemeinkosten</small></article></div></section><?php endif;?>
<section class="erp-card" id="timeline"><div class="erp-section-head"><div><h2>Projekt-Timeline</h2><p class="erp-muted">Die vollständige Geschichte des Projekts.</p></div></div><form class="erp-journal-form" method="post" action="<?=p($url->linkToRoute('reinhardterp.activity.addProjectNote',['projectId'=>$project['id']]))?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><input type="hidden" name="customerId" value="<?=p($project['customer_id'])?>"><textarea name="note" rows="2" placeholder="Interne Notiz …" required></textarea><button class="button primary">Hinzufügen</button></form><?php print_unescaped($this->inc('_activity_timeline',['activities'=>array_slice($activities,0,30)]));?></section>
</main></div></div>
