<?php
require __DIR__.'/_nav.php';
use OCP\IURLGenerator;
$url=\OC::$server->get(IURLGenerator::class);
$s=$_['stats']??[];
?>
<div id="app-content"><div class="erp-page">
 <div class="erp-head"><div><span class="erp-eyebrow">VERKAUF</span><h1>Übersicht</h1><p class="erp-sub">Angebote, Aufträge und Rechnungen auf einen Blick.</p></div><div class="erp-actions"><a class="button primary" href="<?php p($url->linkToRoute('reinhardterp.business.offerForm'));?>">+ Neues Angebot</a></div></div>
 <div class="erp-kpi-grid">
  <a class="erp-kpi-card" href="<?php p($url->linkToRoute('reinhardterp.business.offers'));?>"><span>Offene Angebote</span><strong><?php p((int)($s['offerOpen']??0));?></strong><small><?php p(number_format((float)($s['offerGross']??0),2,',','.').' € brutto');?></small></a>
  <a class="erp-kpi-card" href="<?php p($url->linkToRoute('reinhardterp.business.orders'));?>"><span>Offene Aufträge</span><strong><?php p((int)($s['orderOpen']??0));?></strong><small><?php p(number_format((float)($s['orderGross']??0),2,',','.').' € brutto');?></small></a>
  <a class="erp-kpi-card" href="<?php p($url->linkToRoute('reinhardterp.business.invoices'));?>"><span>Offene Rechnungen</span><strong><?php p((int)($s['invoiceOpen']??0));?></strong><small><?php p(number_format((float)($s['invoiceOpenGross']??0),2,',','.').' € brutto');?></small></a>
  <a class="erp-kpi-card" href="<?php p($url->linkToRoute('reinhardterp.business.invoices'));?>"><span>Bezahlte Rechnungen</span><strong><?php p(number_format((float)($s['invoicePaid']??0),2,',','.').' €');?></strong><small>erfasster Rechnungsstatus</small></a>
 </div>
 <div class="erp-grid-2">
  <section class="erp-card"><div class="erp-section-head"><div><h2>Letzte Angebote</h2></div><a class="button" href="<?php p($url->linkToRoute('reinhardterp.business.offers'));?>">Alle Angebote</a></div><div class="erp-table"><table><thead><tr><th>Nummer</th><th>Kunde</th><th>Status</th><th>Brutto</th></tr></thead><tbody><?php foreach($_['offers'] as $r):?><tr><td><a href="<?php p($url->linkToRoute('reinhardterp.business.offerDetail',['id'=>$r['id']]));?>"><strong><?php p($r['offer_no']);?></strong></a></td><td><?php p($r['customer_name']??'');?></td><td><?php p($r['status']??'');?></td><td><?php p(number_format((float)($r['gross_amount']??0),2,',','.').' €');?></td></tr><?php endforeach;?><?php if(empty($_['offers'])):?><tr><td colspan="4" class="erp-empty">Noch keine Angebote vorhanden.</td></tr><?php endif;?></tbody></table></div></section>
  <section class="erp-card"><div class="erp-section-head"><div><h2>Letzte Aufträge</h2></div><a class="button" href="<?php p($url->linkToRoute('reinhardterp.business.orders'));?>">Alle Aufträge</a></div><div class="erp-table"><table><thead><tr><th>Nummer</th><th>Kunde</th><th>Status</th><th>Brutto</th></tr></thead><tbody><?php foreach($_['orders'] as $r):?><tr><td><a href="<?php p($url->linkToRoute('reinhardterp.business.orderDetail',['id'=>$r['id']]));?>"><strong><?php p($r['order_no']);?></strong></a></td><td><?php p($r['customer_name']??'');?></td><td><?php p($r['status']??'');?></td><td><?php p(number_format((float)($r['gross_amount']??0),2,',','.').' €');?></td></tr><?php endforeach;?><?php if(empty($_['orders'])):?><tr><td colspan="4" class="erp-empty">Noch keine Aufträge vorhanden.</td></tr><?php endif;?></tbody></table></div></section>
 </div>
 <section class="erp-card" style="margin-top:16px"><div class="erp-section-head"><div><h2>Letzte Rechnungen</h2></div><a class="button" href="<?php p($url->linkToRoute('reinhardterp.business.invoices'));?>">Alle Rechnungen</a></div><div class="erp-table"><table><thead><tr><th>Nummer</th><th>Kunde</th><th>Datum</th><th>Status</th><th>Brutto</th></tr></thead><tbody><?php foreach($_['invoices'] as $r):?><tr><td><a href="<?php p($url->linkToRoute('reinhardterp.business.invoiceDetail',['id'=>$r['id']]));?>"><strong><?php p(($r['status']??'')==='draft'?'Entwurf #'.$r['id']:($r['invoice_no']??''));?></strong></a></td><td><?php p($r['customer_name']??'');?></td><td><?php p(!empty($r['invoice_date'])?date('d.m.Y',strtotime((string)$r['invoice_date'])):'');?></td><td><?php p($r['status']??'');?></td><td><?php p(number_format((float)($r['gross_amount']??0),2,',','.').' €');?></td></tr><?php endforeach;?><?php if(empty($_['invoices'])):?><tr><td colspan="5" class="erp-empty">Noch keine Rechnungen vorhanden.</td></tr><?php endif;?></tbody></table></div></section>
</div></div>
