<?php
require __DIR__ . '/_nav.php';
use OCP\IURLGenerator;
$url=\OC::$server->get(IURLGenerator::class);
$users=$_['users']??[];$projects=$_['projects']??[];$rows=$_['rows']??[];$absences=$_['absences']??[];$edit=$_['editEvent']??null;
$names=[];foreach($users as $u)$names[(string)$u['uid']]=(string)$u['displayName'];
$projectNames=[];foreach($projects as $p)$projectNames[(int)$p['id']]=trim((string)($p['project_no']??'').' · '.(string)($p['title']??'').' · '.(string)($p['customer_name']??''));
$projectShort=[];foreach($projects as $p)$projectShort[(int)$p['id']]=trim((string)($p['project_no']??'').' · '.(string)($p['title']??''));
$days=[];$d=new DateTimeImmutable((string)$_['from']);for($i=0;$i<7;$i++)$days[]=$d->modify('+'.$i.' days');
$typeLabels=['vacation'=>'Urlaub','sick'=>'Krank','training'=>'Schulung','other'=>'Abwesend'];
$fmtLocal=static fn(?string $v):string=>$v?date('Y-m-d\\TH:i',strtotime($v)):'';
$editUsers=$edit['assigned_user_ids']??[];
?>
<div id="app-content"><div class="erp-page">
<div class="erp-head"><div><h1 class="erp-help-target" data-betrio-help="staff-planning">Personalplanung</h1><p class="erp-sub">Mitarbeiter auf Projekte und Einsätze einplanen. Genehmigte Abwesenheiten werden direkt mit angezeigt.</p></div></div>
<?php if(!empty($_['error'])):?><div class="erp-notice erp-wide"><strong>Planung konnte nicht gespeichert werden.</strong> <?php p($_['error']);?></div><?php endif;?>
<?php if(!empty($_['success'])):?><div class="erp-integration-state is-connected erp-wide"><span>✓ Gespeichert</span><strong><?php p($_['success']);?></strong></div><?php endif;?>
<div class="erp-card erp-planning-card"><div class="erp-section-head"><div><h2>Woche <?php p(date('d.m.Y',strtotime((string)$_['from'])).' – '.date('d.m.Y',strtotime((string)$_['to'])));?></h2></div><div class="erp-actions"><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.staffPlanning',['week'=>$_['prev']]));?>">← Vorherige</a><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.staffPlanning'));?>">Diese Woche</a><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.staffPlanning',['week'=>$_['next']]));?>">Nächste →</a></div></div>
<div class="erp-planning-grid"><div class="erp-plan-head erp-plan-person">Mitarbeiter</div><?php foreach($days as $day):?><div class="erp-plan-head"><?php p(['So','Mo','Di','Mi','Do','Fr','Sa'][(int)$day->format('w')]);?><small><?php p($day->format('d.m.'));?></small></div><?php endforeach;?>
<?php foreach($users as $u):$uid=(string)$u['uid'];?><div class="erp-plan-person"><strong><?php p($u['displayName']);?></strong></div><?php foreach($days as $day):$date=$day->format('Y-m-d');?><div class="erp-plan-day"><?php $has=false;foreach($absences as $a){if((string)$a['user_id']===$uid&&(string)$a['date_from']<=$date&&(string)$a['date_to']>=$date){$has=true;?><div class="erp-plan-absence"><?php p($typeLabels[$a['type']]??'Abwesend');?></div><?php }}foreach($rows as $r){if(substr((string)$r['start_at'],0,10)!==$date||!in_array($uid,$r['assigned_user_ids']??[],true))continue;$has=true;$pid=(int)($r['project_id']??0);?><a class="erp-plan-event" href="<?php p($url->linkToRoute('reinhardterp.module.staffPlanning',['week'=>$_['from'],'edit'=>(int)$r['id']]));?>" title="Einsatz bearbeiten"><b><?php p(date('H:i',strtotime((string)$r['start_at'])).'–'.date('H:i',strtotime((string)$r['end_at'])));?></b><span><?php p($projectShort[$pid]??(string)$r['title']);?></span><?php if(trim((string)$r['title'])!==''&&isset($projectShort[$pid])):?><small><?php p($r['title']);?></small><?php endif;?></a><?php }if(!$has):?><span class="erp-muted">—</span><?php endif;?></div><?php endforeach;?><?php endforeach;?>
<?php if(!$users):?><div class="erp-empty">Keine aktiven Mitarbeiter vorhanden.</div><?php endif;?></div></div>
<form id="staff-planning-form" class="erp-card" method="post" action="<?php p($url->linkToRoute('reinhardterp.module.saveTeamEvent'));?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><input type="hidden" name="returnTo" value="staff-planning"><input type="hidden" name="confirmConflict" id="confirmConflict" value="0"><?php if($edit):?><input type="hidden" name="eventId" value="<?php p((int)$edit['id']);?>"><?php endif;?><div class="erp-section-head"><h2><?php p($edit?'Einsatz bearbeiten':'Einsatz einplanen');?></h2><?php if($edit):?><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.staffPlanning',['week'=>$_['from']]));?>">Abbrechen</a><?php endif;?></div><div class="erp-form-grid"><div><label>Titel</label><input name="title" required placeholder="z. B. Montage Küche" value="<?php p((string)($edit['title']??''));?>"></div><div><label>Projekt</label><select name="projectId" required><option value="">Projekt auswählen</option><?php foreach($projects as $p):?><option value="<?php p((int)$p['id']);?>" <?php if((int)($edit['project_id']??0)===(int)$p['id'])print_unescaped('selected');?>><?php p($projectNames[(int)$p['id']]);?></option><?php endforeach;?></select></div><div><label>Beginn</label><input type="datetime-local" name="startAt" required value="<?php p($fmtLocal($edit['start_at']??null));?>"></div><div><label>Ende</label><input type="datetime-local" name="endAt" required value="<?php p($fmtLocal($edit['end_at']??null));?>"></div><div><label>Ort</label><input name="location" placeholder="Optional" value="<?php p((string)($edit['location']??''));?>"></div><div><label>Hinweis</label><input name="description" placeholder="Optional" value="<?php p((string)($edit['description']??''));?>"></div></div><fieldset><legend>Mitarbeiter</legend><div class="erp-person-picker"><?php foreach($users as $u):?><label class="erp-person-chip"><input type="checkbox" name="assignedUserIds[]" value="<?php p($u['uid']);?>" <?php if(in_array((string)$u['uid'],$editUsers,true))print_unescaped('checked');?>><span><?php p($u['displayName']);?></span></label><?php endforeach;?></div></fieldset><div class="erp-actions"><button class="button primary" type="submit"><?php p($edit?'Änderungen speichern':'Einsatz speichern');?></button><?php if($edit):?><button class="button" type="submit" form="delete-planning-event" onclick="return confirm('Diesen Einsatz wirklich löschen?');">Einsatz löschen</button><?php endif;?></div></form>
<?php if($edit):?><form id="delete-planning-event" method="post" action="<?php p($url->linkToRoute('reinhardterp.module.deleteTeamEvent',['id'=>(int)$edit['id']]));?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><input type="hidden" name="returnTo" value="staff-planning"></form><?php endif;?>
<p class="erp-muted">Planung und Arbeitszeit bleiben getrennt. Bei Urlaub, Krankheit oder einer zeitlichen Doppelbelegung warnt Betrio vor dem Speichern.</p>
</div></div>
<script>
(function(){const form=document.getElementById('staff-planning-form');if(!form)return;const events=<?php print_unescaped(json_encode(array_map(static fn($r)=>['id'=>(int)$r['id'],'title'=>(string)$r['title'],'start'=>(string)$r['start_at'],'end'=>(string)$r['end_at'],'users'=>$r['assigned_user_ids']??[]],$rows),JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT));?>;const abs=<?php print_unescaped(json_encode(array_map(static fn($a)=>['type'=>(string)$a['type'],'from'=>(string)$a['date_from'],'to'=>(string)$a['date_to'],'user'=>(string)$a['user_id']],$absences),JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT));?>;const current=<?php p((int)($edit['id']??0));?>;form.addEventListener('submit',function(e){if(document.getElementById('confirmConflict').value==='1')return;const start=new Date(form.startAt.value),end=new Date(form.endAt.value),users=[...form.querySelectorAll('input[name="assignedUserIds[]"]:checked')].map(x=>x.value);if(!users.length)return;const conflicts=[];const sd=form.startAt.value.slice(0,10),ed=form.endAt.value.slice(0,10);for(const a of abs)if(users.includes(a.user)&&a.from<=ed&&a.to>=sd)conflicts.push(a.user+' ist abwesend');for(const x of events){if(x.id===current)continue;const xs=new Date(x.start.replace(' ','T')),xe=new Date(x.end.replace(' ','T'));if(start<xe&&end>xs&&x.users.some(u=>users.includes(u)))conflicts.push('Doppelbelegung mit „'+x.title+'“');}if(conflicts.length){e.preventDefault();if(confirm('Planungskonflikt:\n\n'+[...new Set(conflicts)].join('\n')+'\n\nTrotzdem speichern?')){document.getElementById('confirmConflict').value='1';form.submit();}}});})();
</script>
