<?php
require __DIR__.'/_nav.php';
$url=\OC::$server->get(\OCP\IURLGenerator::class);
$s=$_['selected']??[];$view=$_['view']??'overview';$rows=$_['rows']??[];
$materials=$_['supplierMaterials']??[];$documents=$_['supplierDocuments']??[];
$activeCount=count(array_filter($rows,fn($x)=>(int)($x['active']??1)===1));
$materialCount=array_sum(array_map(fn($x)=>(int)($x['material_count']??0),$rows));
$documentCount=array_sum(array_map(fn($x)=>(int)($x['document_count']??0),$rows));
$link=function(string $v,array $extra=[])use($url,$s){return $url->linkToRoute('reinhardterp.module.suppliers',array_merge($s?['id'=>(int)$s['id']]:[],['view'=>$v],$extra));};
?>
<div id="app-content"><div class="erp-page erp-suppliers-v2 erp-suppliers-premium">
<?php if(!empty($_['message'])):?><div class="erp-notice"><?php p($_['message']);?></div><?php endif;?>
<?php if(!$s):?>
<div class="erp-head erp-supplier-head"><div><p class="erp-eyebrow">LAGER & MATERIAL</p><h1>Lieferanten</h1><p class="erp-sub">Lieferanten, Konditionen, Materialien und Belege zentral verwalten.</p></div><div class="erp-actions"><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.materials'));?>">Materialstamm</a><a class="button primary" href="<?php p($url->linkToRoute('reinhardterp.module.suppliers',['view'=>'new']));?>">+ Neuer Lieferant</a></div></div>
<div class="erp-material-summary"><div class="erp-stat"><strong><?php p(count($rows));?></strong><span>Lieferanten</span></div><div class="erp-stat"><strong><?php p($activeCount);?></strong><span>Aktiv</span></div><div class="erp-stat"><strong><?php p($materialCount);?></strong><span>Materialien zugeordnet</span></div><div class="erp-stat"><strong><?php p($documentCount);?></strong><span>Belege zugeordnet</span></div></div>
<section class="erp-supplier-workspace"><form method="get" class="erp-supplier-search"><input type="search" name="q" value="<?php p($_['q']??'');?>" placeholder="Lieferant, Kundennummer, Ansprechpartner oder E-Mail suchen …"><button class="button primary">Suchen</button><?php if(!empty($_['q'])):?><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.suppliers'));?>">Zurücksetzen</a><?php endif;?></form>
<?php if(empty($rows)):?><div class="erp-empty">Keine Lieferanten gefunden.</div><?php else:?><div class="erp-supplier-table"><div class="erp-supplier-row erp-supplier-labels"><span>Lieferant</span><span>Ansprechpartner</span><span>Kontakt</span><span>Konditionen</span><span>Material / Belege</span><span></span></div><?php foreach($rows as $x):?>
<a class="erp-supplier-row" href="<?php p($url->linkToRoute('reinhardterp.module.suppliers',['id'=>$x['id']]));?>"><span class="erp-supplier-main"><strong><?php p($x['name']);?></strong><small><?php p(($x['customer_no']??'')?'Kdnr. '.$x['customer_no']:'Keine Kundennummer');?></small></span><span><?php p($x['contact_person']??'—');?></span><span class="erp-supplier-contact"><?php p($x['phone']??'—');?><small><?php p($x['email']??'');?></small></span><span><?php p($x['payment_terms']??'—');?></span><span><strong><?php p((int)$x['material_count']);?></strong> Material <small>· <?php p((int)$x['document_count']);?> Belege</small></span><span class="erp-row-arrow">›</span></a><?php endforeach;?></div><?php endif;?></section>
<?php elseif($view==='new'):?>
<div class="erp-head erp-supplier-head"><div><p class="erp-eyebrow">LIEFERANTEN</p><h1>Neuer Lieferant</h1><p class="erp-sub">Stammdaten und Konditionen erfassen.</p></div><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.suppliers'));?>">← Zur Übersicht</a></div>
<?php $s=[]; require __DIR__.'/_supplier_form.php'; ?>
<?php else:?>
<div class="erp-head erp-supplier-head"><div><p class="erp-eyebrow">LIEFERANTENAKTE</p><h1><?php p($s['name']);?></h1><p class="erp-sub"><?php p(trim(($s['customer_no']?'Kundennr. '.$s['customer_no'].' · ':'').($s['contact_person']??'')));?></p></div><div class="erp-actions"><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.suppliers'));?>">← Lieferanten</a><a class="button primary" href="<?php p($link('edit'));?>">Bearbeiten</a></div></div>
<nav class="erp-project-tabs erp-supplier-tabs"><a class="<?= $view==='overview'?'active':''?>" href="<?php p($link('overview'));?>">Übersicht</a><a class="<?= $view==='materials'?'active':''?>" href="<?php p($link('materials'));?>">Materialien</a><a class="<?= $view==='documents'?'active':''?>" href="<?php p($link('documents'));?>">Belege</a><a class="<?= $view==='conditions'?'active':''?>" href="<?php p($link('conditions'));?>">Konditionen</a><a class="<?= $view==='notes'?'active':''?>" href="<?php p($link('notes'));?>">Notizen</a><a class="<?= $view==='edit'?'active':''?>" href="<?php p($link('edit'));?>">Mehr</a></nav>
<?php if($view==='edit'): require __DIR__.'/_supplier_form.php'; ?>
<?php elseif($view==='materials'):?><section class="erp-card"><div class="erp-section-head"><div><h2>Materialien</h2><p class="erp-muted">Diesem Lieferanten zugeordnete Artikel.</p></div><a class="button primary" href="<?php p($url->linkToRoute('reinhardterp.module.materials'));?>">Materialstamm öffnen</a></div><?php if(!$materials):?><p class="erp-muted">Keine Materialien zugeordnet.</p><?php else:?><div class="erp-table"><table><thead><tr><th>Artikel</th><th>Bezeichnung</th><th>Gruppe</th><th>EK</th><th>VK</th><th>Bestand</th></tr></thead><tbody><?php foreach($materials as $m):?><tr><td><?php p($m['article_no']??'—');?></td><td><strong><?php p($m['name']);?></strong></td><td><?php p($m['group_name']??$m['material_group']??'—');?></td><td><?php p(number_format((float)($m['purchase_price']??0),2,',','.').' €');?></td><td><?php p(number_format((float)($m['sale_price']??0),2,',','.').' €');?></td><td><?php p(number_format((float)($m['stock_quantity']??0),2,',','.').' '.($m['unit']??''));?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php elseif($view==='documents'):?><section class="erp-card"><h2>Belege</h2><?php if(!$documents):?><p class="erp-muted">Keine Belege zugeordnet.</p><?php else:?><div class="erp-dms-list"><?php foreach($documents as $d):?><a class="erp-dms-row" href="<?php p($url->linkToRoute('reinhardterp.document.detail',['id'=>$d['id']]));?>"><span class="erp-dms-row-main"><strong><?php p($d['document_no']??$d['suggested_document_no']??$d['original_name']??'Beleg');?></strong><small><?php p(($d['document_type']??'Beleg').' · '.substr((string)($d['created_at']??''),0,10));?></small></span><span>›</span></a><?php endforeach;?></div><?php endif;?></section>
<?php elseif($view==='conditions'):?><section class="erp-card erp-supplier-detail-grid"><div><h2>Konditionen</h2><dl><dt>Zahlungsziel</dt><dd><?php p($s['payment_terms']??'—');?></dd><dt>Kundennummer</dt><dd><?php p($s['customer_no']??'—');?></dd><dt>IBAN</dt><dd><?php p($s['iban']??'—');?></dd><dt>BIC</dt><dd><?php p($s['bic']??'—');?></dd></dl></div><div><h2>Adresse</h2><p><?php p($s['street']??'');?><br><?php p(trim(($s['postal_code']??'').' '.($s['city']??'')));?><br><?php p($s['country']??'');?></p></div></section>
<?php elseif($view==='notes'):?><section class="erp-card"><h2>Notizen</h2><div class="erp-note-box"><?php p($s['notes']??'Keine Notizen hinterlegt.');?></div></section>
<?php else:?><div class="erp-material-summary"><div class="erp-stat"><strong><?php p(count($materials));?></strong><span>Materialien</span></div><div class="erp-stat"><strong><?php p(count($documents));?></strong><span>Belege</span></div><div class="erp-stat"><strong><?php p(($s['active']??1)?'Aktiv':'Inaktiv');?></strong><span>Status</span></div><div class="erp-stat"><strong><?php p($s['payment_terms']??'—');?></strong><span>Zahlungsziel</span></div></div><div class="erp-supplier-overview"><section class="erp-card"><h2>Kontakt</h2><dl><dt>Ansprechpartner</dt><dd><?php p($s['contact_person']??'—');?></dd><dt>Telefon</dt><dd><?php if(!empty($s['phone'])):?><a href="tel:<?php p($s['phone']);?>"><?php p($s['phone']);?></a><?php else:p('—');endif;?></dd><dt>E-Mail</dt><dd><?php if(!empty($s['email'])):?><a href="mailto:<?php p($s['email']);?>"><?php p($s['email']);?></a><?php else:p('—');endif;?></dd><dt>Website</dt><dd><?php p($s['website']??'—');?></dd></dl></section><section class="erp-card"><h2>Adresse & Konditionen</h2><p><?php p($s['street']??'');?><br><?php p(trim(($s['postal_code']??'').' '.($s['city']??'')));?><br><?php p($s['country']??'');?></p><p><strong>Zahlungsziel:</strong> <?php p($s['payment_terms']??'—');?></p></section><section class="erp-card"><h2>Notiz</h2><p><?php p($s['notes']??'Keine Notiz hinterlegt.');?></p></section></div><?php endif;?>
<?php endif;?>
</div></div>
