<?php require __DIR__.'/_nav.php'; use OCP\IURLGenerator; $url=\OC::$server->get(IURLGenerator::class); $users=$_['users']??[]; $roles=$_['roles']??[]; $rates=$_['hourlyRates']??[]; $active=0;$admins=0;$field=0; foreach($users as $u){$e=$roles[$u['uid']]??['role'=>($u['isAdmin']?'admin':'employee'),'enabled'=>true]; if($u['isAdmin']||(bool)($e['enabled']??true))$active++; if(($e['role']??'')==='admin'||$u['isAdmin'])$admins++; if(in_array(($e['role']??''),['employee','time'],true))$field++;} ?>
<div id="app-content"><div id="app-content-wrapper"><div class="erp-page erp-team-workspace">
<div class="erp-project-hero"><div><span class="erp-project-eyebrow">MITARBEITER · TEAM</span><h1>Mitarbeiter</h1><p>Benutzer, Rollen und Stundensätze zentral verwalten.</p></div><div class="erp-project-hero-actions"><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.teamEvents'));?>">Teamkalender</a><a class="button primary" href="<?php p($url->linkToRoute('reinhardterp.module.timeEvaluation'));?>">Zeitauswertung</a></div></div>
<nav class="erp-customer-tabs erp-team-tabs"><a class="is-active" href="<?php p($url->linkToRoute('reinhardterp.module.users'));?>">Übersicht</a><a href="<?php p($url->linkToRoute('reinhardterp.module.timeEvaluation'));?>">Zeiterfassung</a><a href="<?php p($url->linkToRoute('reinhardterp.module.teamEvents'));?>">Teamkalender</a></nav>
<div class="erp-kpis erp-team-kpis"><div><span>Mitarbeiter</span><strong><?php p(count($users));?></strong><small>Nextcloud-Benutzer</small></div><div><span>Aktiv</span><strong><?php p($active);?></strong><small>Betrio-Zugriff</small></div><div><span>Monteure / Zeit</span><strong><?php p($field);?></strong><small>operative Rollen</small></div><div><span>Administratoren</span><strong><?php p($admins);?></strong><small>Vollzugriff</small></div></div>
<div class="erp-notice erp-wide erp-team-hint"><strong>Hinweis:</strong> Neue Mitarbeiter müssen sich einmal mit ihrem eigenen Konto in Nextcloud anmelden. Danach können Rolle, Zugriff und Stundensatz hier festgelegt werden.</div>
<div class="erp-team-list"><div class="erp-team-list-head"><span>Mitarbeiter</span><span>Zugriff & Rolle</span><span>Stundensatz</span><span></span></div>
<?php foreach($users as $u): $entry=$roles[$u['uid']]??['role'=>($u['isAdmin']?'admin':'employee'),'enabled'=>true,'hourly_rate_id'=>null,'individual_hourly_rate'=>null]; $role=$entry['role'];$enabled=$u['isAdmin']?true:(bool)$entry['enabled']; $initial=mb_strtoupper(mb_substr((string)$u['displayName'],0,1)); ?>
<form class="erp-team-row" method="post" action="<?php p($url->linkToRoute('reinhardterp.module.saveUserRole'));?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']);?>"><input type="hidden" name="userId" value="<?php p($u['uid']);?>">
<div class="erp-team-person"><span class="erp-customer-mini-avatar"><?php p($initial);?></span><div><strong><?php p($u['displayName']);?></strong><small><?php p($u['uid']);?><?php if($u['isAdmin']):?> · Nextcloud-Administrator<?php endif;?></small></div></div>
<div class="erp-team-access"><select name="enabled" <?=$u['isAdmin']?'disabled':''?>><option value="1" <?=$enabled?'selected':''?>>Aktiv</option><option value="0" <?=!$enabled?'selected':''?>>Gesperrt</option></select><?php if($u['isAdmin']):?><input type="hidden" name="enabled" value="1"><?php endif;?><select name="role"><option value="admin" <?=$role==='admin'?'selected':''?>>Administrator</option><option value="office" <?=$role==='office'?'selected':''?>>Büro</option><option value="manager" <?=$role==='manager'?'selected':''?>>Projektleiter</option><option value="employee" <?=$role==='employee'?'selected':''?>>Angestellter</option><option value="time" <?=$role==='time'?'selected':''?>>Nur Zeiterfassung</option></select></div>
<div class="erp-team-rate"><select name="hourlyRateId"><option value="">Keine Gruppe</option><?php foreach($rates as $rate):if(empty($rate['active']))continue;?><option value="<?php p($rate['id']);?>" <?php if((int)($entry['hourly_rate_id']??0)===(int)$rate['id'])echo 'selected';?>><?php p($rate['name'].' · '.number_format((float)$rate['sales_rate'],2,',','.').' €');?></option><?php endforeach;?></select><input type="number" min="0" step="0.01" name="individualHourlyRate" value="<?php p($entry['individual_hourly_rate']??'');?>" placeholder="individuell €"></div><button class="button primary" type="submit">Speichern</button></form>
<?php endforeach;?></div>
<div class="erp-card erp-wide erp-team-price"><strong>Preislogik</strong><span>Festgeschriebener Satz → Projekt-Sonderpreis → Mitarbeitersatz → Stundengruppe → manueller Ersatzsatz.</span></div>
</div></div></div>
