<?php
require __DIR__.'/_nav.php';
use OCP\IURLGenerator;
$url=\OC::$server->get(IURLGenerator::class);
\OCP\Util::addScript('reinhardterp','material_rows');
$prev=date('Y-m-d',strtotime($_['weekStart'].' -7 days'));
$next=date('Y-m-d',strtotime($_['weekStart'].' +7 days'));
$materialCatalog=array_map(static fn(array $m):array=>[
 'id'=>(int)$m['id'],'article_no'=>(string)($m['article_no']??''),'name'=>(string)$m['name'],'unit'=>(string)($m['unit']??''),'price'=>(float)($m['price']??0),'sale_price'=>(float)($m['sale_price']??$m['price']??0)
],$_['materials']);
?>
<script type="application/json" id="erp-material-catalog"><?=json_encode($materialCatalog,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?></script>
<datalist id="erp-material-options"><?php foreach($_['materials'] as $m): ?><option value="<?php p(trim(($m['article_no']??'').' · '.$m['name'],' ·')); ?>"><?php endforeach; ?></datalist>
<div id="app-content"><div class="erp-page"><h1>Zeiterfassung</h1><p class="erp-sub">Arbeitszeit und verbautes Material gemeinsam erfassen. Beides wird später zusammen in den Rapport und in die Abrechnung übernommen.</p>
<div class="erp-time-toolbar"><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.workdays',['week'=>$prev])); ?>">‹ Vorwoche</a><strong><?php p(date('d.m.Y',strtotime($_['weekStart'])).' – '.date('d.m.Y',strtotime($_['weekEnd']))); ?></strong><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.workdays',['week'=>$next])); ?>">Nächste Woche ›</a><a class="button" href="<?php p($url->linkToRoute('reinhardterp.module.workdays')); ?>">Diese Woche</a></div>
<div class="erp-cards erp-time-summary"><div class="erp-card"><span>Wochenstunden</span><strong><?php p(number_format((float)$_['weekSummary']['total'],2,',','.')); ?></strong></div><?php foreach($_['weekSummary']['users'] as $uid=>$hours): ?><div class="erp-card"><span><?php p($uid); ?></span><strong><?php p(number_format((float)$hours,2,',','.')); ?> h</strong></div><?php endforeach; ?></div>
<h2>Projekt-Timer</h2>
<?php if($_['activeTimers']): ?><div class="erp-timers"><?php foreach($_['activeTimers'] as $t): ?><div class="erp-timer-card"><div><strong><?php p($t['user_id'].' · '.($t['project_no']??'').' '.($t['title']??'')); ?></strong><p><?php p($t['activity']); ?></p><small>Gestartet: <?php p(date('d.m.Y H:i',strtotime($t['started_at']))); ?> · Status: <?php p($t['status']==='paused'?'Pause':'läuft'); ?></small></div><div class="erp-timer-actions"><?php if($t['status']==='running'): ?><form method="post" action="<?php p($url->linkToRoute('reinhardterp.module.pauseTimer',['id'=>$t['id']])); ?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']); ?>"><button class="button">Pause</button></form><?php else: ?><form method="post" action="<?php p($url->linkToRoute('reinhardterp.module.resumeTimer',['id'=>$t['id']])); ?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']); ?>"><button class="button">Weiter</button></form><?php endif; ?><form method="post" action="<?php p($url->linkToRoute('reinhardterp.module.stopTimer',['id'=>$t['id']])); ?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']); ?>"><button class="button primary">Feierabend / Stop</button></form></div></div><?php endforeach; ?></div><?php endif; ?>
<form class="erp-form-card" method="post" action="<?php p($url->linkToRoute('reinhardterp.module.startTimer')); ?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']); ?>"><div class="erp-form-grid"><div><label>Mitarbeiter / Monteur</label><select name="userId" required><option value="">Mitarbeiter wählen</option><?php foreach($_['users'] as $u): ?><option value="<?php p($u['uid']); ?>" <?=$u['uid']===$permissions->uid()?'selected':''?>><?php p($u['displayName'].' · '.$u['uid']); ?></option><?php endforeach; ?></select></div><div><label>Projekt</label><select name="projectId" required><option value="">Projekt wählen</option><?php foreach($_['projects'] as $p): ?><option value="<?php p($p['id']); ?>"><?php p($p['project_no'].' · '.$p['title']); ?></option><?php endforeach; ?></select></div><div class="erp-span-2"><label>Tätigkeit</label><textarea name="activity" rows="4" required placeholder="Was wird ausgeführt?"></textarea></div></div><h3>Material zum Timer</h3><p class="erp-muted">Material kann direkt mit dem Timer erfasst werden. Sobald eine Zeile ausgefüllt wird, erscheint automatisch die nächste.</p><div class="erp-material-entry-list" data-material-rows></div><button class="button primary">▶ Zeit starten</button></form>
<h2>Manuelle Zeiterfassung</h2>
<form class="erp-form-card" method="post" action="<?php p($url->linkToRoute('reinhardterp.module.saveWorkday')); ?>"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']); ?>"><div class="erp-form-grid"><div><label>Mitarbeiter / Monteur</label><select name="userId" required><option value="">Mitarbeiter wählen</option><?php foreach($_['users'] as $u): ?><option value="<?php p($u['uid']); ?>" <?=$u['uid']===$permissions->uid()?'selected':''?>><?php p($u['displayName'].' · '.$u['uid']); ?></option><?php endforeach; ?></select></div><div><label>Datum</label><input type="date" name="workDate" value="<?php p(date('Y-m-d')); ?>" required></div><div><label>Projekt</label><select name="projectId" required><option value="">Projekt wählen</option><?php foreach($_['projects'] as $p): ?><option value="<?php p($p['id']); ?>"><?php p($p['project_no'].' · '.$p['title']); ?></option><?php endforeach; ?></select></div><div><label>Beginn</label><input type="time" name="startTime"></div><div><label>Ende</label><input type="time" name="endTime"></div><div><label>Pause in Minuten</label><input type="number" min="0" name="breakMinutes" value="0"></div><div><label>Stunden (alternativ)</label><input type="number" step="0.25" min="0" name="hours" value="0"><small>0 = automatische Berechnung.</small></div><div class="erp-span-2"><label>Tätigkeit</label><textarea name="activity" rows="8" required placeholder="Ausführlich beschreiben, was ausgeführt wurde …"></textarea></div><div class="erp-span-2"><label>Interne Notiz</label><textarea name="notes" rows="3"></textarea></div></div><h3>Verbrauchtes / verbautes Material</h3><p class="erp-muted">Suche nach Artikelnummer oder Bezeichnung. Freie Positionen sind ebenfalls möglich.</p><div class="erp-material-entry-list" data-material-rows></div><button class="button primary">Zeit und Material speichern</button></form>
<div class="erp-table"><table><thead><tr><th>Datum</th><th>Mitarbeiter</th><th>Projekt</th><th>Stunden</th><th>Tätigkeit</th><th>Material</th><th>Rapport</th><th></th></tr></thead><tbody><?php foreach($_['rows'] as $r): ?><tr><td><?php p(date('d.m.Y',strtotime($r['work_date']))); ?><br><small><?php p(trim(($r['start_time']??'').'–'.($r['end_time']??''),'–')); ?></small></td><td><?php p($r['user_id']); ?></td><td><?php p(($r['project_no']??'').' · '.($r['title']??'')); ?></td><td><strong><?php p(number_format((float)($r['hours']??0),2,',','.')); ?></strong></td><td class="erp-activity"><?php p($r['activity']??''); ?></td><td><?php if(empty($r['materials'])): ?><span class="erp-muted">—</span><?php else: ?><ul class="erp-material-summary"><?php foreach($r['materials'] as $m): ?><li><?php p(number_format((float)$m['quantity'],3,',','.').' '.($m['unit']??'').' '.$m['description']); ?></li><?php endforeach; ?></ul><?php endif; ?></td><td><?php if($r['imported_to_report_id']): ?><span class="erp-badge">Übernommen</span><?php else: ?><span class="erp-muted">offen</span><?php endif; ?></td><td><?php if(!$r['imported_to_report_id']): ?><form method="post" action="<?php p($url->linkToRoute('reinhardterp.module.deleteWorkday',['id'=>$r['id']])); ?>" onsubmit="return confirm('Zeiteintrag und Material wirklich löschen?')"><input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']); ?>"><button class="button icon-delete" title="Löschen"></button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
